.github/workflows/test.yml
GitHub made mac11 out of private beta! 
Now we can run tests on XCode 13 which is swift 5.5. Ubuntu 20 is still on swift 5.4 (understandable, 5.5 beta) so we don't test swift 5.5 on the Linux environment yet.
=> ci: update to mac11

.github/workflows/deploy-sdk.yml, .releaserc.json, update_version.sh
The version of the SDK is in the swift source code so it can be used in the SDK. 
Since we automate deployments, we need to automate changing the SDK version, too.
=> ci: update SDK version during deployment

Sources/Tracking/Store/SdkCredentialsStore.swift, Sources/Tracking/Util/KeyValueStorageKey.swift, Tests/Shared/XCTestCaseExtensions.swift, Tests/Tracking/Store/SdkConfigStoreTest.swift
What if there is a scenario when we need to iterate all of the site ids ever registered with the SDK? Up until this PR, you can't. We use site ids as the keys to getting a key/value storage store. If we ever need to iterate all of the key/value stores, for example, then we need to have all of those site ids persisted.
Potential use cases of needing this:
* Migrations to data stored in key/value storage.
* When a background queue is added to the SDK, the background queues may be separated by the site ids. It's important that we send all of that data for all site ids up to the API so we need to know all of the site ids registered with the SDK to sync all of the data for all sites.
﻿
=> feat: save all siteids registered with SDK

Sources/MessagingPush/MessagingPush.swift, Sources/Tracking/CustomerIO.swift, Sources/Tracking/Tracking.swift, Tests/Tracking/CustomerIOTest.swift
Using `shared` is the common naming in the community + Apple's SDKs for singletons. ﻿
=> fix: rename singletons instance to shared

Sources/MessagingPush/MessagingPush.swift, Sources/Tracking/Extensions/StringExtensions.swift
The current way of converting the APN device token to string does not work. This fixes that.
=> fix: convert APN device token to string

Sources/MessagingPush/MessagingPush.swift, Tests/MessagingPush/MessagingPushTest.swift, Tests/Tracking/VersionTest.swift
To be consistent with identifying a profile function, call the callback function on the main thread for APN token functions.
=> fix: call callback on main thread APN tokens

Sources/MessagingPush/MessagingPush.swift, Sources/Tracking/Service/HttpEndpoint.swift, Tests/Tracking/VersionTest.swift
Deleting a device token was not working where the request body was not readable by the API.
=> fix: remove apn device token profile request body

Sources/MessagingPushAPN/MessagingPush+APN.swift, Sources/MessagingPushAPN/autogenerated/AutoMockable.generated.swift
Adds an overload to the `registerDeviceToken` func on the `MessagingPushAPN` class for those who want to call it directly instead of using our wrapper
=> chore: register apn device token Data

Sources/Tracking/DeviceInfo.swift, Sources/Tracking/Extensions/DeviceExtension.swift, Sources/Tracking/Service/HttpClient.swift, Tests/Tracking/Service/HttpClientTest.swift
[Issue 6245](https://github.com/customerio/issues/issues/6245) 
This PR contains : 
- Add value of user-agent in header which can be easily parsed by the backend
- Format followed : `Customer.io iOS Client/1.0.0-alpha.16 (x86_64; iOS 14.5) User App/1.0`
- In case UIKit is unavailable : `Customer.io iOS Client/1.0.0-alpha.16`
Manual testing done on :
=> fix: improve user-agent with more detail

Sources/Tracking/Util/Log.swift
To better improve the QA experience of the team, log messages now show up in the macOS Console app instead of just the Xcode console. This allows the team to be able to view logs for pre-built versions of the app and not just builds built in Xcode.
=> fix: logs now show up in mac console app

Sources/Tracking/CustomerIOImplementation+ScreenViews.swift, Sources/Tracking/CustomerIOImplementation.swift
This PR contains fix for screen view tracking.
Since iOS 13, Apple introduced Scene Delegates along with App Delegate which is now used to manage life cycle methods in an app. Screen view tracking was compatible to work with App Delegate but not scene delegates.
fix : Screen view tracking works with scene delegate apps
=> fix: screen view tracking

Sources/Tracking/Store/SiteId.swift, Sources/Tracking/Util/Log.swift, Sources/Tracking/autogenerated/AutoDependencyInjection.generated.swift
When the SDK is used with multiple CIO Workspaces (such as in the Remote Habits app), the SDK logs are difficult to understand. When an event happens, it's hard to see if the event is being recorded for workspace A or workspace B. 
This change adds to the logs the siteId that the event happens for to make debugging issues easier.
=> fix: add siteid to logs help with multi-workspace

.github/FAIL_COCOAPODS_DEPLOY_ISSUE_TEMPLATE.md, .github/workflows/deploy-cocoapods.yml, scripts/push-cocoapod.sh
Right now, if the CI is pushing to cocoapods and the retry limit is reached, the script will gracefully shut down and report that the cocoapod pushed successfully. 
This PR makes the script fail if the max retry limit reached. 
This PR was made because the latest push to cocoapods hit it's retry limit but I didn't catch it because the CI's status is saying the script ran successfully. https://github.com/customerio/customerio-ios/actions/runs/1785461160
Complete each step to get your pull request merged in. [Learn more about the workflow this project uses](https://github.com/customerio/customerio-ios/develop/docs/dev-notes/GIT-WORKFLOW.md).
=> ci: prevent false positives pushing cocoapods script

Sources/Tracking/CustomerIO.swift, Tests/Tracking/CustomerIOImplementationTest.swift
Customer is reporting issue is still happening: https://github.com/customerio/customerio-ios/issues/134#issuecomment-1031532870 where tracking events is generating `data:null` JSON request bodies. 
A [previous bug fix](https://github.com/customerio/customerio-ios/commit/04c5211ac83592e7191d7313a61e37cea8be38fa) was created to combat this issue with a test case to reproduce the error. However, the test resulted in a false positive because the test function only tested calling `CustomerIOImplementation.track()` and not calling `CustomerIO.track()`. When changing the test function to call `CustomerIO.track()` the bug was able to be reproduced and show that it still exists.
=> fix: create valid JSON request body when sending nil as track events data

.github/workflows/deploy-git-tag.yml
Part of [`git-flow`](https://nvie.com/posts/a-successful-git-branching-model/) is that once you make a production deployment, you merge those commits back into your `develop` branch. I forgot to add this step to [my previous git-flow PR](https://github.com/customerio/customerio-ios/pull/133). This PR adds this task in where commits added to `main` will be merged into `develop` after a production deployment. 
=> ci: copy deployed commits into develop after main deployments

Sources/MessagingPush/util/DeviceAttributesProvider.swift, Tests/MessagingPush/util/DeviceAttributesProviderTest.swift
This fix is related to [PR #143](https://github.com/customerio/customerio-ios/pull/143) and [this](https://github.com/customerio/issues/issues/6510) ticket. 
minor fix to change property name (from list of default device attributes) from `push_subscribed` to `push_enabled` 
=> fix: change property name from push_subscribed to push_enabled

Sources/Tracking/Util/DeviceInfo.swift
Currently, the device locale that the SDK obtains is the current locale of the host app. This has limitations on it because if the user's device is set to Spanish but the host app does not support Spanish, the device locale that the SDK receives is not Spanish. 
We want to improve our SDK's code in regards to obtaining the device locale. We would prefer is we get the locale of the device even if the host app does not support it. That's what this PR is doing. 
=> fix: locale uses preferred language

Sources/Tracking/Type/Aliases.swift
While developing remote habits, I experienced a moment where some classes could not be imported from the SDK. These classes exist in the `Common` module which we do not suggest customers `import` in their source code. The solution is to make these classes `public` and visible in one of the SDKs (probably the `Tracking` one). 
This PR fixes the issue by exporting the classes from the `Tracking` module. This fixed the issue with remote habits where now importing the Tracking module in the remote habits source code can now find these classes. I prefer to have the `Common` module be written in a more generic form where it does not contain classes the other SDKs require, but it would take a bigger refactor to be able to make these classes exported in this PR to no longer be needed in the …
=> fix: some classes not found in tracking module

Sources/MessagingPush/MessagingPushImplementation.swift, Sources/Tracking/CustomerIOImplementation.swift, Sources/Tracking/Util/JsonAdapter.swift
Fix to production SDK to fix bug where custom attributes with keys in all caps gets sent to API with snackcase. Example: send "CITY" to the SDK and SDK converts this key to "c_ity". 
This PR is simply the bug fix itself. It does not include tests. I created [another PR](https://github.com/customerio/customerio-ios/pull/169) that is meant to get merged into `develop` that includes all of the tests for this PR. I tried to add the tests to this PR but there was a bit of complexity because of many utility classes created in `develop` that's not in `main`. 
=> fix: send attributes in all caps to API

Sources/Tracking/CustomerIO.swift, Sources/Tracking/CustomerIOImplementation.swift, Tests/Tracking/CustomerIOImplementationTest.swift
This PR enables Gist SDK in-app routing with automatic screen view tracking.  SDK was setup for only manually recorded screen views. Now that the iOS SDK has more stable automatic screenview reporting, we can enable routing for both manual and automatic screenview tracking. 
=> feat: enable gist routing for automatic screenviews

Sources/Common/Type/SDKWrapperConfig.swift
SdkWrapperConfig is inaccessible right now to modules outside it's scope such as using it in react native package. The fix is to make SdkWrapperConfig accessible.
=> fix: make sdkwrapperconfig accessible

.github/workflows/deploy-cocoapods.yml
Deployment to Cocoapods failed because the module CustomerIOTracking depends on CustomerIOCommon and this module is missing in the deployment workflow. Because CustomerIOTracking could not be published, subsequent podspecs dependent on it also could not get deployed. 
Here is the error screenshot for reference.
Updated workflow and added CustomerIOCommon podspec. Note that the series of podspecs to be run is important. Because CustomerIOTracking depends on CustomerIOCommon, this is why CustomerIOCommon is added to the start of push list followed by other podspecs.
=> ci: add customeriocommon podspec to cocoapod deployment

Sources/MessagingPushAPN/MessagingPushAPN.swift
[Slack conversation](https://customerio.slack.com/archives/C03F7C5KQ4C/p1661347252603109?thread_ts=1661188398.751329&cid=C03F7C5KQ4C)
**Issue :**
Rich push notification was not showing image in the notification.
**Fix:**
The function was pointing to wrong instance which caused recursive calls & hence failed to show image in the push.
=> fix: image not shown in rich push notification

Sources/MessagingPush/MessagingPushImplementation.swift
[Slack conversation](https://customerio.slack.com/archives/C01QYDKD0SU/p1661158061399669)
**Issue**
Customers registering their device from iPad were not getting listed under devices because the expected platforms are `iOS/Android`.
**Fix**
Consolidating all Apple platforms under `iOS` 
=> fix: consolidate all apple platforms under ios

Sources/Common/Type/SDKWrapperConfig.swift
**Added enum values for Expo and Flutter (so that we don't have to make a update for flutter, the next SDK in queue)**
=> fix: added expo and flutter values in source enum

Sources/Common/Extensions/UIApplicationExtensions.swift, Sources/Tracking/CustomerIOImplementation+ScreenViews.swift
Fixes: https://secure.helpscout.net/conversation/2063138194/182158
Xcode gives compile-time errors unless certain annotations are added to the code. This bug has been fixed in the past, but was not tested in the configuration that the customer is using (cocoapods with FCM). 
=> fix: fix compile time errors notification service extensions

CustomerIOMessagingPushFCM.podspec
Breaking change introduced: 
* Customers impacted: React Native customers using FCM. That's because if they follow our docs as they appear today, we do not tell customers to install Firebase dependencies on their own with cocoapods. So, by RN customers upgrading the iOS SDK to include this change, they will need to install the firebase SDK themselves. 
~~Needs to be tested:~~ [done](https://github.com/customerio/customerio-ios/pull/210#issuecomment-1305794706)
* Create new iOS app that uses cocoapods
* Install [this PR](https://github.com/customerio/customerio-ios/issues/203#issuecomment-1303787347)
* Integrate FCM
* Run app and see if receive a rich push
This PR fixes [this customer reported issue](https://github.com/customerio/customerio-ios/issues/203). Our original action item was to …
=> refactor!: remove FCM dependency from cocoapods

Sources/Tracking/CustomerIO.swift
I found this bug while updating our sample apps with `2.0.0-alpha.1`. 
=> fix: sdk not able to compile in ios app

Sources/Common/Store/SdkConfig.swift
Forgot this SDK config option in our `2.0.0-alpha.1` release. We might need it for wrappers such as RN. 
=> fix: add sdkwrapperconfig to rich push SDK config

Sources/Tracking/CustomerIO.swift, Tests/MessagingInApp/MessagingInAppIntegrationTest.swift
Fixes: https://github.com/customerio/customerio-ios/issues/242
v1.2.8 has a bug where the diGraph instance isn't populated (when it should) in `CustomerIO` class. 
This PR refactors the `CustomerIO` class to populate the diGraph when the SDK is being initialized.
=> fix: 1.2.8 initialize in-app with debug logs no longer crashes SDK

Tests/MessagingInApp/MessagingInAppIntegrationTest.swift
- tests: reproduce bug
- tests: reproduce 1.2.8 bug in v2 to see if exists
=> test: reproduce 1.2.8 bug in v2 to see if exists

Sources/Common/Background Queue/QueueRunRequest.swift, Sources/Common/autogenerated/AutoDependencyInjection.generated.swift, Sources/Common/autogenerated/AutoLenses.generated.swift, Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/MessagingInApp/autogenerated/AutoMockable.generated.swift, Sources/MessagingPush/autogenerated/AutoMockable.generated.swift, Sources/MessagingPushAPN/autogenerated/AutoMockable.generated.swift, Sources/MessagingPushFCM/autogenerated/AutoMockable.generated.swift, Sources/Templates/AutoMockable.stencil, Sources/Tracking/autogenerated/AutoDependencyInjection.generated.swift, Sources/Tracking/autogenerated/AutoMockable.generated.swift, Tests/Common/Background Queue/QueueRunRequestTest.swift, Tests/Shared/XCTestCaseExtensions.swift
Closes: https://github.com/customerio/customerio-ios/issues/248
2.0.2 could encounter an infinite loop and eventually stackoverflow while executing the background queue. This was because the BQ while loop would has an infinite loop running while not waiting for the *async HTTP request* to finish. Running async code in a while loop requires some extra logic that was previously not present. 
Automated unit test added that verifies the BQ while loop runs async tasks in sequential order without causing an infinite loop. 
Still todo:
=> fix: async running BQ operations in loop

CustomerIOMessagingInApp.podspec, Package.resolved, Package.swift
We missed this and only updated the `SPM`
=> fix: update the gist version in podspec

Sources/Common/Service/Request/PushMetric.swift
To be able to be used from wrappers it needs not to be internal. 
=> fix: access modifier for metric

Sources/Common/Store/SdkConfig.swift
I didn't realize until reading [this pr](https://github.com/customerio/customerio-flutter/pull/21/) that it's quite important that we keep the `SdkConfig.Keys` object `public` and keep the values backwards compatible for the SDK wrappers. 
Added a comment to note this.
=> docs: add note SDK wrappers using constants in SdkConfig

.github/workflows/deploy-sdk.yml
Fixes a release tag variable leftover from #261. Since the workflow is no longer triggered on a release, it needs to be adjusted.
=> ci: fix deploy action slack variable

.github/workflows/deploy-sdk.yml
The github plugin being used by semantic-release will comment on each PR when a deployment is finished, so we need `pull_requests: write` permission.
=> ci: add comment permissions for semantic release bot

.github/workflows/deploy-sdk.yml
Related to #261, we actually want to keep the `beta` branch around for deployments for a little while longer.
=> ci: add beta branch to deploy workflow

scripts/cocoapods_override_sdk.rb
This PR adds a re-usable script for `Podfile` that our SDK wrappers can use. My hope is the comments in the script explain this PR. If there are questions or concerns about this PR, I will update the description in the script to try and explain it better. 
For an example on how to use this script, see [this PR](https://github.com/customerio/amiapp-reactnative/pull/54).
=> refactor: create cocoapods script to make sdk override easier in sdk wrappers

Sources/Tracking/CustomerIO.swift, Sources/Tracking/CustomerIOImplementation.swift, Sources/Tracking/autogenerated/AutoMockable.generated.swift, Tests/Tracking/APITest.swift, Tests/Tracking/CustomerIOIntegrationTests.swift
Our sample apps allow you to change the SDK behavior at runtime. In our sample apps, we have a settings screen that allows you to view the currently set SDK configuration values with the ability to modify the values. 
This PR adds a feature to the iOS SDK that allows the sample apps to add this settings screen feature. The sample apps are able to get the currently set SDK config values to display on the screen.
=> feat: expose current SDK config options for reference

.github/workflows/deploy-sdk.yml, Apps/CocoaPods-FCM/Podfile
Because cocoapods deployments are flaky at the moment, we still need the ability to manually triggger cocoapods deployments on the CI server. 
We should be able to merge this PR and then manually trigger a 2.5 deployment.
=> ci: allow manually deploying to cocoapods from existing tag

scripts/cocoapods_override_sdk.rb
@Shahroz16 only merge if you find that Ami RN iOS builds are fixed and no longer show the Gist compile-time errors.
=> build: fix SDK wrappers not compiling because in-app SDK installing in NSE

.github/workflows/deploy-sdk.yml
deploy-sdk CI workflow when running on `main` branch is currently broken. 
I thought that `brew` would *just work* when running on Linux but I did not know that [you have to enable it before running](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#homebrew-note).
=> ci: fix deploy-sdk workflow not running because homebrew not installed

CustomerIOMessagingInApp.podspec, Package.swift
Since updates to Gist aren't currently being tested on wrappers, and with more exciting major updates coming through for Gist. We are auto-updating only `minor/patch` releases. 
More context can be found here: https://customerio.slack.com/archives/C01QYDKD0SU/p1684186998625329?thread_ts=1684138499.569099&cid=C01QYDKD0SU
=> fix: minor only auto update for gist

.github/workflows/build-sample-apps.yml, Apps/fastlane/Fastfile
At this time, sample apps are only being built for pull requests. However, these can be unstable. We need the ability to download *stable* versions of our sample apps for work that is completed. 
This PR makes builds of the sample apps when PRs are merged to the `main` branch.
=> ci: build sample apps on main branch pushes

Apps/APN-UIKit/APN UIKit/AppDelegate.swift, Apps/APN-UIKit/APN UIKit/SceneDelegate.swift
If you click a push notification with a Universal Link deep attached in the UIKIt app today, the browser will open instead of the app. 
The sample app was missing [a function from the documentation](https://customer.io/docs/sdk/ios/push/#universal-links-deep-links). With this added `AppDelegate` function, the app opens Universal Links instead of the browser. 
Currently, [the sample app builds made in this PR are not able to be tested](https://customerio.slack.com/archives/C01QYDKD0SU/p1684776299768119). The testing thus far has been my own QA testing on my computer.
=> refactor: uikit sample universal links in push open app, not browser

Apps/fastlane/Fastfile
This improves compatibility of our iOS CI configuration for building sample apps to work better with the SDK wrappers.
=> ci: fix Info.plist file editing to only modify project files, not dependency files

.github/workflows/build-sample-apps.yml, .github/workflows/deploy-sdk.yml, Apps/fastlane/Fastfile
When building sample apps, builds are either considered stable or unstable. We like to separate the two so unstable builds go to our squad members and stable goes to everyone else. That way we can avoid non-squad members from installing unstable builds of our apps we make. 
Previously, I setup the CI to make stable app builds when a new git tag was made. However, I have since noticed that this method has consequences to it and takes more work. 
This PR instead changes our CI sample apps building to consider all builds on the `main`  branch to be stable. 
- Before merging, make a PR on Android SDK repo to test against this branch. Make sure sample apps build on Android successfully from this branch. 
- I have tested this[ branch against …
=> ci: sample apps to stable test group when merge on main

dangerfile.js
Closes: https://github.com/customerio/issues/issues/9257
* `danger pr https://github.com/customerio/customerio-ios/pull/303` failed because that PR only modified 1 of the files. 
* `danger pr https://github.com/customerio/customerio-ios/pull/333` passed because both files were modified.
=> ci: fix danger rules not catching SPM and cocoapods rule

Apps/CocoaPods-FCM/src/View/Appium.swift, Apps/CocoaPods-FCM/src/View/DashboardView.swift, Apps/CocoaPods-FCM/src/View/LoginView.swift, Apps/CocoaPods-FCM/src/View/SettingsView.swift, Apps/CocoaPods-FCM/test cocoapods.xcodeproj/project.pbxproj, Apps/Common/Source/Manager/CioSettingsManager.swift, Apps/Common/Source/Model/CioSettings.swift
Part of: https://github.com/customerio/issues/issues/9818
Sets identifiers to each of the existing Views in the app for Appium tests to reference. 
I am not sure how to run Appium tests against the sample app to verify that I used the correct method of adding IDs to views for Appium to use. So I am not sure [if the method I used](https://github.com/customerio/customerio-ios/pull/334/files#diff-d67db103c287986efd5bb55c8b0d335544d1e5ac4aa1c57cd6364a33c44fbe4aR7) is correct. However, since the logic is encapsulated, we should be able to fix issues with 1 line of code. 
I see that linter has failed on PR because of a `TODO` I added. I plan to add the back button in a future PR. This PR is not being merged into `main` so I plan to keep this lint error and fix it in future PR before `main` …
=> refactor: setup Appium tags for Swift UI sample app

Apps/CocoaPods-FCM/Podfile, CustomerIOMessagingPushFCM.podspec, Package.swift, dangerfile.js
This PR was inspired by recent conversations in Slack and also [in a RN SDK PR](https://github.com/customerio/customerio-reactnative/pull/149#discussion_r1230945251). 
Including the FCM SDK as a dependency in our iOS SDK adds benefits to the SDK. Mostly, easier setup. 
The consequences of adding the FCM SDK as a dependency is version issues. If the FCM SDK is specified multiple times in a `Podfile` and the version requirements do not match, then cocoapods throws an error. We experienced this in the past which is why we removed the FCM SDK. This PR does not include a version requirement at all meaning that we support the latest version. 
Native iOS customers and SDK wrapper customers all are asked to manually add the FCM SDK to their `Podfile`. We made this recommendation to allow …
=> feat: include FCM SDK as a dependency to make FCM push setup easier

Apps/fastlane/Fastfile
The `()` in user-agent might cause problems with our backend parsing user-agent. [Learn more](https://customerio.slack.com/archives/C01QYDKD0SU/p1686069849968289?thread_ts=1686002124.298969&cid=C01QYDKD0SU)
=> ci: sample apps user-agent compatible with backend

Apps/APN-UIKit/APN UIKit/View/Customisation/CustomDataViewController.swift
No required fields for custom events, device attributes and profile attributes in sample apps so that positive and negative test cases can be covered.
=> refactor: improvement - optional fields for custom events, device and profile attributes

Apps/APN-UIKit/APN UIKit/Util/DeepLinksHandlerUtil.swift, Sources/MessagingInApp/MessagingInAppImplementation.swift
fixes: https://github.com/customerio/customerio-reactnative/issues/161
=> fix: wrong thread when invoking webview 

.github/workflows/test.yml, Sources/Tracking/CustomerIOImplementation.swift
=> fix: save device token in SDK even if no profile identified

Apps/CocoaPods-FCM/Podfile, Apps/CocoaPods-FCM/Rich Push Notification Service Extension/NotificationService.swift, Apps/CocoaPods-FCM/src/AppDelegate.swift, Apps/Common/Source/Model/CioSettings.swift, Sources/Common/DIGraph.swift, Sources/Common/Util/Lock.swift, Sources/Tracking/CustomerIO.swift, Tests/MessagingInApp/MessagingInAppIntegrationTest.swift, Tests/Shared/Stub/ThreadUtilStub.swift, Tests/Tracking/CustomerIOIntegrationTests.swift, Tests/Tracking/CustomerIOTest.swift
This reverts commit 0483fb04e02228bfe1dd1ff88e9e51e688b477fd.
=> fix: apps initializing sdk multiple times in short amount of time may make SDK ignore requests 

Sources/Common/Util/StringAnyEncodable.swift, Sources/Tracking/CustomerIO.swift, Sources/Tracking/CustomerIOImplementation.swift, Tests/Common/Util/StringAnyEncodable.swift, Tests/Tracking/CustomerIOImplementationTest.swift
fixes: https://github.com/customerio/issues/issues/10475
- Updated `StringAnyEncodable` to encode arrays recursively
=> fix: support json array in attributes

Apps/CocoaPods-FCM/src/View/SettingsView.swift
Fix/Improvements to
- hide keyboard on tapping `Save` button on Settings screen
- background queue validations 
- restore default settings on tapping `Restore defaults` on Settings screen
=> refactor: fcm swiftui sample app consistency

Apps/CocoaPods-FCM/src/View/SettingsView.swift
In the settings screen, the siteid and apikey key were not restoring to defaults. This PR fixes this bug.
=> refactor: fcm swiftui sample siteid, apikey restore defaults

Sources/Common/Background Queue/QueueStorage.swift, Sources/Common/Store/QueueInventoryMemoryStore.swift, Sources/Common/autogenerated/AutoDependencyInjection.generated.swift, Tests/Common/Background Queue/QueueStorageTest.swift
Part of https://github.com/customerio/issues/issues/10950
This PR introduces a cache for the BQ inventory. This cache reduces the number of times the SDK needs to read the BQ inventory from the file system. This reduction in file system writes reduces the CPU usage of the SDK while the BQ runs.
=> fix: cache queue inventory for lower CPU usage while running queue

.github/workflows/build-sample-apps.yml
Part of ticket https://github.com/customerio/issues/issues/11139
To verify that customers can compile their apps with our SDK installed, this PR enables Xcode15 beta builds on the CI. 
I expect that once 15 goes stable, we can make 15 the default and drop compiling on CI with 14. 
I checked the [CI logs](https://github.com/customerio/customerio-ios/actions/runs/5904453500/job/16016675787?pr=373) and it looks like it ran as expected. The latest Xcode 15 beta 6 got installed and fastlane used xcode 15 for compiling the app.
=> ci: build with xcode 15 beta

.github/workflows/deploy-sdk.yml
SDK is experiencing [known issue of semantic-release](https://github.com/semantic-release/commit-analyzer/issues/517) to exit early before deployment is performed. 
This PR implements workaround.
=> ci: set workaround for semantic-release issue skipping deployment

Sources/Common/Extensions/StringExtensions.swift, Sources/Common/Service/CIOApiEndpoint.swift, Tests/Common/Service/HttpEndpointTest.swift
closes: https://github.com/customerio/customerio-reactnative/issues/191
=> fix: added url path encoding

Sources/Common/Background Queue/QueueRunRequest.swift, Tests/Common/Background Queue/QueueRunRequestTest.swift
Through reviewing a set of SDK debug logs recently, I noticed the queue can get into an edge case that prevents it from ever finishing. Blocking the queue from running any more tasks while the app is in memory. 
I was able to reproduce the issue through a test and then implemented a bug fix.
=> fix: when queue cannot find task, expect queue runs next task

Apps/CocoaPods-FCM/src/View/SettingsView.swift, Sources/Tracking/CustomerIO.swift, Sources/Tracking/CustomerIOImplementation.swift, Sources/Tracking/autogenerated/AutoMockable.generated.swift, Tests/Tracking/CustomerIOImplementationTest.swift
To fetch the already stored device token from the SDK. 
This feature will require the customer to write the code (as they do today) in AppDelegate to register the device when the token is generated. This feature **_does not_** auto save the token.
This PR is an attempt to elevate https://github.com/customerio/issues/issues/11181.
1.
- Launch iOS app 
- Login into the app
- Tap on settings button on the top-right corner
- Check if device token shown in device token field
2.
- Launch iOS app 
- Tap on settings button on the top-right corner
- Check if device token shown in device token field
=> feat: get currently registered device token

Sources/Tracking/CustomerIO.swift, Tests/Tracking/CustomerIOIntegrationTests.swift
This is a bug fix to resolve [issue reported by React Native customer](https://github.com/customerio/customerio-reactnative/issues/168). 
- I created integration test to reproduce the issue. The test suite crashes when running the newly added test. 
- I wrote the bug fix in the `CustomerIO` class. Test passes after bug fix implemented.
=> fix: memory exception during SDK initialization async tasks

.github/workflows/deploy-sdk.yml, .github/workflows/test.yml
Deployments on `main` are currently broken because of a GH action that we use. 
This PR updates the GH action to an action that I have found to work. This is a workaround to get deployments working again until the original GH action gets fixed.
=> ci: fix installing sd tool needed for deployment

Apps/CocoaPods-FCM/Podfile, Sources/MessagingPushAPN/MessagingPushAPN+PushConfigs.swift
Fixes: https://github.com/customerio/customerio-ios/issues/178#issuecomment-1821464983
The CI server was not able to catch this bug for us because this bug is specific to APN and cocoapods. Our CI server is only testing cocoapods and FCM. 
This PR modifies CI tests to now test for APN compilation as well to prevent bugs like this in future.
=> fix: cocoapods APN customers app not compiling

Sources/MessagingPush/MessagingPush.swift, Sources/MessagingPush/MessagingPushConfigOptions.swift, Sources/MessagingPush/PushClickHandler.swift, Sources/MessagingPush/autogenerated/AutoDependencyInjection.generated.swift, Sources/MessagingPushAPN/MessagingPushAPN.swift, Sources/MessagingPushFCM/MessagingPushFCM.swift
Merges into: https://github.com/customerio/customerio-ios/pull/403
Because the SDK will now be automatically handling when a push from CIO is clicked on, the SDK is also responsible for determining if a push is shown while app is in foreground or not. 
Previously, [customers specified this in their host app themselves](https://github.com/customerio/customerio-ios/blob/a2ccebf1dae6d891c8c699005a083a4147241130/Apps/CocoaPods-FCM/src/AppDelegate.swift#L56-L64). Now that customers will no longer need these code in their AppDelegate file, then customers can configure this behavior via SDK config. 
- add config option to docs
=> feat: show a push while app in foreground

Sources/MessagingPush/PushHandling/iOSPushEventListener.swift, Sources/MessagingPush/autogenerated/AutoDependencyInjection.generated.swift, Tests/MessagingPush/PushHandling/PushClickHandlerTest.swift
fixing all lint errors in `levi/reliable-open-metrics` branch
=> refactor: get lint passing

Sources/MessagingPush/MessagingPush.swift, Sources/MessagingPush/MessagingPushConfigOptions.swift, Tests/MessagingPush/IntegrationTest.swift, Tests/MessagingPush/MessagingPushTest.swift
In a team call, we discussed the importance of customers being able to disable this feature if they need to. We do not anticipate a customer needing to do this, but because this feature does involve techniques such as swizzling, it's good practice to give customers the option to disable the functionality if they encounter issues in their app's edge case environment.
=> feat: disable the feature, if a customer needs to

Tests/MessagingPush/MessagingPushTest.swift, Tests/MessagingPush/PushHandling/ManualPushHandlingTest.swift
I have noticed this test function is a bit flaky when running on the CI. 
CI servers are less powerful machines so having the test take a little longer to pass makes sense. 
I don't recommend running the test function less < 100 times so I thought that bumping up the `wait()` function was the best solution. I don't like making a test suite take longer to execute (by bumping the wait() time), but a test suite that sometimes catches bugs and sometimes doesn't (by decreasing the number of times the test runs) sounds worse 🤷‍♀️.
=> test: fix flaky test

Sources/MessagingPush/PushHandling/ManualPushHandling.swift, Sources/MessagingPush/PushHandling/PushClickHandler.swift, Sources/MessagingPush/autogenerated/AutoDependencyInjection.generated.swift, Sources/Tracking/CustomerIO.swift, Tests/MessagingPush/IntegrationTest.swift, Tests/MessagingPush/MessagingPushTest.swift, Tests/MessagingPush/PushHandling/ManualPushHandlingTest.swift, Tests/MessagingPush/PushHandling/PushClickHandlerTest.swift
Fixes a bug I discovered. See [comment](https://github.com/customerio/customerio-ios/pull/438/files#r1428173254) that explains bug. 
Added automated tests to verify bug fix.
=> fix: manual push click handling may not track opened metric

Sources/MessagingPush/PushHandling/AutomaticPushClickHandling.swift, Sources/MessagingPush/PushHandling/iOSPushEventListener.swift, Sources/MessagingPush/autogenerated/AutoDependencyInjection.generated.swift
To help us support this feature for customers, I added debug log statements. 
These debug log statement's job is to give us enough information so we can try and reproduce a issue that the customer is experiencing. The logs are not meant to document every line of code executed within this feature. 
Besides the logs added in this PR, a debug log entry already exists when a new UNUserNotificationCenterDelegate gets set on the host app. All of these debug statements combined are the most helpful debug statements I can think of at this time.
=> refactor: add debug logs to help support feature

Apps/APN-UIKit/APN UIKit/AppDelegate.swift, Apps/CocoaPods-FCM/src/AppDelegate.swift, Sources/Common/Util/KeyValueStorageKey.swift, Sources/MessagingPush/Extensions/NotificationCenterExtensions.swift, Sources/MessagingPush/PushHandling/iOSPushEventListener.swift, Sources/MessagingPush/Store/PushHistory.swift, Sources/MessagingPush/autogenerated/AutoDependencyInjection.generated.swift, Sources/MessagingPush/autogenerated/AutoMockable.generated.swift, Tests/MessagingPush/Store/PushHistoryTest.swift
This PR [as well as APN sample app setup PR](https://github.com/customerio/customerio-ios/pull/443) adds support for local push notifications [to the reliable opened push metrics feature](https://github.com/customerio/issues/issues/11289). 
The current implementation has a bug that could make handling local push notifications not work. 
* Local push notification with a hard-coded/non-unique identifier is displayed on the device. 
* Push gets clicked. 
* Host app is able to handle that local push getting clicked. 
* Local push notification with a hard-coded/non-unique identifier is displayed on the device. 
* Push gets clicked. 
* Host app is able to handle that local push getting clicked *one time*. 
* If you try and display the local push 2+ times and click on it, the host app will not …
=> fix: add support for local notifications

Apps/APN-UIKit/APN UIKit/AppDelegate.swift, Apps/APN-UIKit/APN UIKit/Base.lproj/Main.storyboard, Apps/APN-UIKit/APN UIKit/View/DashboardViewController.swift, Apps/CocoaPods-FCM/src/AppDelegate.swift, Sources/Common/Util/KeyValueStorageKey.swift, Sources/MessagingPush/Extensions/NotificationCenterExtensions.swift, Sources/MessagingPush/PushHandling/iOSPushEventListener.swift, Sources/MessagingPush/Store/PushHistory.swift, Sources/MessagingPush/autogenerated/AutoDependencyInjection.generated.swift, Sources/MessagingPush/autogenerated/AutoMockable.generated.swift, Tests/MessagingPush/Store/PushHistoryTest.swift
The APN sample app currently does not have a way to test 3rd party click handlers are called. The FCM sample apps all do as well as RN APN and Expo APN. This is the last app that needs a way to test this. 
I added a new button to the UI of the app that when you press it, it displays a local push notification on the device that you can click on. When you click it, you should see that the `AppDelegate` click handler callback functions get called to handle this push getting clicked. 
For FCM sample apps, we can use [firebase console](https://console.firebase.google.com/u/0/project/remote-habits/notification/compose) to send a FCM push that is not sent from CIO for testing. For APN, a tool like that does not exist. We instead use local push to test pushes sent not from CIO.
=> refactor: setup apn sample app to test local push

Sources/Common/Communication/Event.swift
Broken down and reworked PR for the Event Bus implementation.
More Details about the previous implementation can be found in the previous [PR](https://github.com/customerio/customerio-ios/pull/440)
PR 1: Holds the events models
=> chore: event bus representable pr1

Sources/DataPipeline/DataPipelineImplementation.swift
helps: https://github.com/customerio/issues/issues/11609
- Updated track metric event name from `Journeys Delivery Metric` to `Report Delivery Event`, the payload remains the same ([slack thread](https://customerio.slack.com/archives/C01QYDKD0SU/p1702680918308849))
- Removed TODO as the name has been confirmed
=> chore: metric event name update

Sources/Tracking/CustomerIO.swift, Sources/Tracking/autogenerated/AutoDependencyInjection.generated.swift, Sources/Tracking/migration/AnalyticsMigrationAssistant.swift, Sources/Tracking/migration/DataPipelineMigrationAssistant.swift
- Updated shared implementation instance to refer `DataPipeline.shared` directly
- Removed `CustomerIOImplementation` class
- Introduced `DataPipelineMigrationAssistant` class to hold all migration related code for CIO customers migrating to newer releases
=> chore: moved migration code to helper

Apps/APN-UIKit/APN UIKit/View/LoginViewController.swift, Sources/Common/CustomerIOInstance.swift
This PR fixes the following scenario: 
Sample app was crashing in a scenario where the user sends `nil` value for body in `identify` method. The specific use case is when a user clicks `Generate Random Login` and attempts to login without a body. 
=> fix: app crash on identify method

Apps/README.md
Someone on TS team informed me about a typo in the docs for how to compile sample apps.
=> docs: fix typo for sample app compilation

Sources/Common/Util/RingBuffer.swift, Tests/Common/Util/RingBufferTest.swift
Broken down PR for https://github.com/customerio/customerio-ios/pull/454/files#top
Please go through the details in the parent ticket for further context.
=> test: ringbuffer for event memory cache

Package.swift, Sources/DataPipeline/DataPipeline.swift, Tests/DataPipeline/DataPipelineInteractionTests.swift, Tests/DataPipeline/Support/TestUtilities.swift
helps: https://github.com/customerio/issues/issues/11965
- Setting up tests environment for `DataPipeline`
- Updated `DataPipeline` so it can work with fake instances
- Added support methods to make testing `DataPipeline` easier
- Changed the name from `CustomerIOImplementationTest` to `DataPipelineInteractionTests` so it is easier to track updated tests
_**Note:** This is the main PR where we'll add more test changes later on_
=> chore: data pipeline tests base setup

Sources/Common/Communication/EventBusHandler.swift, Sources/Common/autogenerated/AutoDependencyInjection.generated.swift
=> fix: eventbus handler ref

Sources/DataPipeline/CustomerIO.swift, Sources/DataPipeline/DataPipeline.swift, Sources/DataPipeline/DataPipelineImplementation.swift, Sources/Tracking/CustomerIO.swift, Tests/Common/Service/UserAgentUtilTest.swift, Tests/DataPipeline/DataPipelineImplementation+ScreenViewsTest.swift, Tests/DataPipeline/DataPipelineInteractionTests.swift, Tests/DataPipeline/Support/TestUtilities.swift, Tests/Shared/IntegrationTest.swift, Tests/Shared/UnitTest.swift, Tests/Shared/extension/CustomerIOExtension.swift, Tests/Tracking/migration/DataPipelineMigrationAssistantTests.swift
helps: https://github.com/customerio/issues/issues/11965
- Added helper methods for setting up fake/mocked instances for `DataPipeline` tests
- Fixes and improvements in base `UnitTest` and `IntegrationTest` classes
- Fixed broken test for `last_used` attribute
=> chore: data pipeline tests base improvements

Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/MessagingInApp/Gist/Gist.swift, Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift, Sources/Tracking/autogenerated/AutoMockable.generated.swift
The idea is to keep track of the shown messages by queueId (which is unique per message) and skip the shown ones
This is based on the same solution applied for gist-web: https://github.com/customerio/gist-web/pull/26
Task: https://github.com/customerio/issues/issues/11967
=> fix: ensure messages are only shown once

Sources/MessagingPush/MessagingPush.swift, Sources/MessagingPush/MessagingPushConfigOptions.swift, Sources/MessagingPush/MessagingPushImplementation.swift, Sources/MessagingPush/RichPush/MessagingPush+RichPush.swift, Sources/MessagingPush/RichPush/RichPushDeliveryTracker.swift, Sources/MessagingPush/RichPush/RichPushHttpClient.swift, Sources/MessagingPush/RichPush/RichPushRequestHandler.swift, Sources/MessagingPush/autogenerated/AutoDependencyInjection.generated.swift
helps: https://linear.app/customerio/issue/MOB-13/http-layer-for-nse
root ticket: https://github.com/customerio/issues/issues/11953
TLDR (work required): We need to add an HTTP layer that exists in the `Messaging Push` module when a push is received in NSE, we can just use that HTTP client to track the delivery for us. HTTP client is going to use the CIO data pipeline API endpoint. 
Currently, HTTP client implementation was meant to stay in the `common` layer, but not anymore, if we are only utilizing the HTTP client rich push notification, downloading URL/ tracking metric. The implementation should be `Messaging` module-specific as well.  
This PR does the following:
- Add HTTP client implementation in the Messaging Push since it's the only module that utilizes it. 
- Add logic for …
=> chore: added rich push delivery tracking

Sources/Tracking/autogenerated/AutoMockable.generated.swift, Tests/Common/Extensions/DateExtensionTests.swift
Fixed date extension test case that was failing due to timezone difference.
=> chore: fix dateextension test case based on timezone

Apps/APN-UIKit/APN UIKit/AppDelegate.swift, Sources/MessagingPush/MessagingPushConfigOptions.swift
closes https://linear.app/customerio/issue/MBL-85/remove-occurrence-of-autotrackdeviceattributes-from-all-push-modules
Includes:
- Remove all instances of unused property autoTrackDeviceAttributes from the MessagingPush, MessagingPushAPN
- Update sample apps using this property from any of push modules
=> fix: remove occurrence of autoTrackDeviceAttributes from all push modules

Sources/Common/Util/DeviceInfo.swift, Sources/Tracking/CustomerIOImplementation+ScreenViews.swift
This PR does not introduce any functional changes. It only aimed at handling warnings and compile error due to deprecated APIs and one removed API in VisionOS 1.0
- Manually build APN UIKit app to make sure the compiled code is not stripped out for iOS and device locale new API works as expected
- Same on VisionOS which uses SwiftUI. `keyWindow` call is stripped out
=> chore: OS conditions for removed and deprecated APIs

Sources/MessagingInApp/MessagingInAppImplementation.swift, Sources/MessagingInApp/Provider/InAppProvider.swift, Sources/MessagingInApp/autogenerated/AutoMockable.generated.swift
Currently, Gist is following a different logger than CIO. This PR just enabled gist logging in case CIO logging is enabled. 
More context: https://customerio.slack.com/archives/C01QYDKD0SU/p1707896913866299
=> fix: enable logging for gist

Sources/MessagingPush/PushHandling/PushEventHandlerProxy.swift, Tests/MessagingPush/PushHandling/PushEventHandlerTest.swift
Closes: https://linear.app/customerio/issue/MBL-70/assert-that-sdk-does-not-forward-push-click-events-to-itself
The CIO SDK push event handler forwards events to other handlers in the host app, allowing multiple push SDKs to be installed simultaneously.
However, forwarding events back to the CIO SDK push event handler could cause an infinite loop. A previous solution to prevent this was removed as it was fragile and not a good long-term fix. This commit adds a test to simulate the scenario to make sure an infinite loop will not occur.
Luckily, the push notification history feature prevents an infinite loop! No additional fix is needed.
Link to code that prevents infinite loop: https://github.com/customerio/customerio-ios/blob/55df69c3200c61bf2abaaa136a70d5de009ea7f0/Sources/MessagingPush/P …
=> test: prevent infinite loop if sdk forwards push event back to itself

Sources/MessagingPushAPN/Aliases.swift, Sources/MessagingPushFCM/Aliases.swift, Tests/DataPipeline/APITest.swift, Tests/MessagingPushAPN/APITest.swift, Tests/MessagingPushFCM/APITest.swift, Tests/Tracking/APITest.swift
helps: [MBL-103](https://linear.app/customerio/issue/MBL-103/public-api-remove-existing-initialization-method-using-siteid-and)
- Added alias for `MessagingPushConfigOptions` to `FCM` and `APN`
- Moved old `APITest` from `Tracking` to appropriate modules including `DataPipeline`, `MessagingPushAPN` and `MessagingPushFCM`
=> chore: fixed api tests for old initialization

Sources/DataPipeline/DataPipelineImplementation.swift, Sources/DataPipeline/Plugins/DeviceAttributes.swift, Tests/DataPipeline/DataPipelineInteractionTests.swift, Tests/DataPipeline/Support/Segment.swift
closes: https://linear.app/customerio/issue/MBL-107/automatic-device-attributes
If `autoTrackDeviceAttributes` is `enabled` we need to restrict Segment added attributes as well.
=> chore: automatic device attributes cleanup

Sources/MessagingPush/UserNotificationsFramework/Wrappers.swift
When debugging the sample apps, you will see SDK debug statements when a push event occurs:
(siteid:xyz) Push event: willPresent. push: CioMessagingPush.UNNotificationWrapper
(siteid:xyz) On push action event. push action: CioMessagingPush.UNNotificationResponseWrapper
These log statements are not very useful because they do not actually tell us what the contents are of `UNNotificationWrapper`, for example.
Swift `structs` when they are printed include values of the properties inside of them. So, the debug logs are much more valuable if we change the data types to structs.
I tested this change with sample apps.
commit-id:4aeb187e
=> refactor: improve debug logs for UserNotification framework classes

Sources/DataPipeline/Type/Aliases.swift
To provide logLevel, folks shouldn't need to add the `CioCommon` dependency.
=> chore: added alias for loglevel

Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/Tracking/migration/DataPipelineMigrationAssistant.swift, Tests/DataPipeline/APITest.swift, Tests/DataPipeline/DataPipelineCompatibilityTests.swift, Tests/DataPipeline/DataPipelineInteractionTests.swift, Tests/Tracking/APITest.swift, Tests/Tracking/CustomerIOMockTest.swift, Tests/Tracking/migration/DataPipelineMigrationAssistantTests.swift
helps: [MBL-102](https://linear.app/customerio/issue/MBL-102/public-api-deprecate-tracking-apis-to-trigger-compile-time-errors)
- Auto generated file updates from #537 
- Fixed tests broken due to changes in mentioned PR
- Updated public api tests to match the expectations
=> chore: fix tests for deprecated tracking apis

Sources/Common/CustomerIOInstance.swift, Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/DataPipeline/CustomerIO.swift, Sources/DataPipeline/DataPipeline.swift, Sources/DataPipeline/DataPipelineImplementation.swift, Tests/Common/CustomerIOTest.swift, Tests/DataPipeline/Core/UnitTest.swift, Tests/Shared/Core/UnitTestBase.swift, Tests/Tracking/APITest.swift, Tests/Tracking/Core/UnitTest.swift
closes: https://linear.app/customerio/issue/MBL-123/remove-postinitialize-from-common
Decouples `postInitialize` from `DIGraph`
=> chore: refactored post initialize to be independent of digraph

Sources/Common/Background Queue/Queue.swift, Sources/Common/Background Queue/QueueStorage.swift, Sources/Common/Util/FileStorage.swift, Sources/Common/autogenerated/AutoDependencyInjection.generated.swift, Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/Tracking/autogenerated/AutoMockable.generated.swift, Sources/Tracking/migration/DataPipelineMigrationAssistant.swift, Tests/Common/Util/FileStorageTest.swift, Tests/DataPipeline/DataPipelineImplementation+ScreenViewsTest.swift, Tests/Shared/SampleData/SampleDataFilesUtil.swift, Tests/Shared/extension/QueueStorageExtension.swift, Tests/Tracking/migration/DataPipelineMigrationAssistantTests.swift, Tests/Tracking/migration/QueueExtension.swift
Closes: https://linear.app/customerio/issue/MBL-126/de-couple-bq-migration-from-sdkconfig
`SdkConfig.siteId` parameter is going away. So, we need to decouple classes `SdkConfig` when they need a `siteId`. Instead, these classes will be provided a `siteId` through function parameters.
Starting at the DataPipe migration class, I added a `siteId` parameter. Then, modified all dependencies of the migration class until the code compiled. Most of the code that changed was the BQ file storage and all of it's tests.
commit-id:8ca21f6c
=> refactor: decouple BQ from SdkConfig

Sources/Common/Service/HttpRequestRunner.swift, Tests/Shared/HttpTest.swift
more context: https://www.loom.com/share/971cb87f0216460faa0cefbf4fc9591e
and similar merged PR for cdp, where this issue was found : https://github.com/customerio/customerio-ios/pull/551
=> fix: rich push image downloading path conflict when its already downloaded

Tests/DataPipeline/Core/UnitTest.swift, Tests/DataPipeline/DataPipelineInteractionTests.swift, Tests/MessagingPush/HttpTest.swift, Tests/Tracking/Core/UnitTest.swift
part of: https://linear.app/customerio/issue/MBL-101/ensure-initilization-key-match-ui
Some PRs were merged after completing above ticket and were added/modified or for some reason were using `writeKey` instead of `cdpApiKey`. This PR caters to it and makes the use of  `cdpApiKey` in all test cases.
=> refactor: use cdpApiKey in iOS SDK remaining test cases

Sources/Common/Module/ModuleTopLevelObject.swift, Sources/DataPipeline/DataPipeline.swift, Sources/MessagingInApp/MessagingInApp.swift, Sources/MessagingPush/MessagingPush.swift, Tests/Common/Module/ModuleTopLevelObjectTest.swift, Tests/MessagingPush/MessagingPushTest.swift
Closes: https://linear.app/customerio/issue/MBL-129/sdk-modules-can-only-be-initialized-1-time
All SDK modules have a top-level `ModuleName.initialize()` function. We have a SDK requirement that this function is only executed one time and ignore all future calls.
This change brings a few improvements to this requirement:
1. Move implementation into base class, `ModuleTopLevelObject`, to encapsulate the logic and allow re-use by all SDK modules.
2. Adds automated tests for `ModuleTopLevelObjectTest` super class to assert that our code only allows initializing modules one time. Note: These tests were originally written in `MessagingPushTest` and were moved to new `ModuleTopLevelObjectTest` class.
commit-id:63854a04
=> fix: all sdk modules can only be initialized once

Sources/Common/Util/LockManager.swift, Sources/DataPipeline/Plugins/AutoTrackingScreenViews.swift, Sources/DataPipeline/autogenerated/AutoDependencyInjection.generated.swift, Tests/DataPipeline/DataPipelineImplementation+ScreenViewsTest.swift
Closes: https://linear.app/customerio/issue/MBL-130/automatic-screen-view-feature-causing-multiple-events-tracked
The SDK keeps track of the last screen automatically tracked. If the new screenview event is equal to this last screen tracked, ignore the request.
The linear ticket gives context on why this solution was chosen over alternative approaches.
commit-id:336b0aff
=> fix: prevent duplicate automatic screenview events from being tracked

Sources/Common/Service/Request/MetricRequest.swift, Sources/MessagingPush/PushHandling/ManualPushHandling+UserNotifications.swift, Sources/MessagingPushAPN/autogenerated/AutoDependencyInjection.generated.swift
No functional changes in this PR.
Fixed 3 lint warnings
- Removed 2 unused variables
- Removed non-existing import which is reported as ignored
Built and ran APN UIKit sample app.
I am not sure if the non-existing import removal have impact on other non-native wrappers though. If it is, then I will revert this line from this PR as it would need to be conditioned appropriately
=> chore: minor lint warnings removed

Sources/Common/Service/CIOApiEndpoint.swift, Sources/Common/Type/Region.swift, Sources/DataPipeline/Config/SDKConfigBuilder.swift, Sources/DataPipeline/Type/Region.swift, Tests/DataPipeline/Config/SDKConfigBuilderTest.swift
closes: [MBL-152](https://linear.app/customerio/issue/MBL-152/add-region-support-to-cdp-config)
- Exposes `Region` option in `SDKConfigBuilder` for conveniently setting `apiHost` and `cdnHost` for `US` and `EU` regions
- Updated tests for `Region` changes
- Remove old API url and relevant code from `Region`
=> chore: add region to sdk config builder

Apps/VisionOS/VisionOS.xcodeproj/project.pbxproj, Apps/VisionOS/VisionOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Apps/VisionOS/VisionOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Apps/VisionOS/VisionOS/Assets.xcassets/AccentColor.colorset/Contents.json, Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Back.solidimagestacklayer/Content.imageset/Contents.json, Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Back.solidimagestacklayer/Contents.json, Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Contents.json, Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Front.solidimagestacklayer/Content.imageset/Contents.json, Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Front.solidimagestacklayer/Contents.json, Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Middle.solidimagestacklayer/Content.imageset/Contents.json, Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Middle.solidimagestacklayer/Contents.json, Apps/VisionOS/VisionOS/Assets.xcassets/Contents.json, Apps/VisionOS/VisionOS/Info.plist, Apps/VisionOS/VisionOS/MainScreen.swift, Apps/VisionOS/VisionOS/Preview Content/Preview Assets.xcassets/Contents.json, Apps/VisionOS/VisionOS/VisionOSApp.swift, Sources/Common/Service/Request/MetricRequest.swift
docs: [vision-os-sample-app][1/n] Skeleton app
This is the first PR in a series of PRs to build sample app that runs Identify and Track in VisionPro
In this PR I created a new VisionOS project in Xcode, did some cleanup for things we won’t use, and added the 3 dependencies I will use throughout the app:
- `customerio` local dependency for Identify and Track
- `splash` for code syntax highlight theme that will be used in the app for code snippets
- `swift-markdown-ui` will be used to enable markdown for the tutorials content
- Open `VisionOs.xcproject`
- Hit CMD+R to run the project and make sure you have VisionOS simulator installed and selected
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with …
=> docs: [vision-os-sample-app][1/n] Skeleton app

Sources/DataPipeline/CustomerIO.swift, Tests/DataPipeline/APITest.swift, Tests/DataPipeline/Config/SDKConfigBuilderTest.swift, Tests/DataPipeline/Core/UnitTest.swift, Tests/DataPipeline/DataPipelineInteractionTests.swift, Tests/MessagingPushAPN/APITest.swift, Tests/MessagingPushFCM/APITest.swift
- Fixed tests breaking due to reinitialization of `analytics` with same `writeKey`
- Fixed `logLevel` for `DataPipeline` module
=> chore: fix data pipeline tests

Apps/APN-UIKit/APN UIKit/AppDelegate.swift, Apps/CocoaPods-FCM/src/AppDelegate.swift, Apps/Common/Source/Model/CioSettings.swift, Sources/DataPipeline/Config/DataPipelineConfigOptions.swift, Sources/DataPipeline/Config/SDKConfigBuilder.swift, Sources/DataPipeline/CustomerIO.swift, Sources/DataPipeline/DataPipelineImplementation.swift, Tests/DataPipeline/APITest.swift, Tests/DataPipeline/Config/SDKConfigBuilderTest.swift
closes: https://linear.app/customerio/issue/MBL-162/change-siteid-to-migrationsiteid-in-datapipelineconfigoptions
Renamed siteId to migrationSiteId in following areas:
- DataPipelineConfigOptions
- SDK config build
- Sample apps
=> chore: rename siteId

Sources/Common/Communication/EventBusHandler.swift, Sources/Common/Util/TaskBag.swift, Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/DataPipeline/autogenerated/AutoMockable.generated.swift, Sources/MessagingInApp/autogenerated/AutoMockable.generated.swift, Sources/MessagingPush/autogenerated/AutoMockable.generated.swift, Sources/MessagingPushAPN/autogenerated/AutoMockable.generated.swift, Sources/MessagingPushFCM/autogenerated/AutoMockable.generated.swift, Sources/Migration/autogenerated/AutoMockable.generated.swift, Sources/Templates/AutoMockable.stencil, Tests/MessagingInApp/MessagingInAppImplementationTest.swift, Tests/Shared/Core/UnitTestBase.swift, Tests/Shared/Mocks/EventBusHandler.swift, Tests/Shared/extension/EventBusExtensions.swift
Part of: https://linear.app/customerio/issue/MBL-95/improve-test-suite-compatibility-with-async-eventbus-operations
As part of improving test suite compatibility with the EventBus, this refactor reduces flakiness by replacing the async operations in tearDown() with synchronous operations. The async code (`Task {}`) in the synchronous function (`deleteAllPersistentData`) is not guaranteed to complete by the time tearDown() is complete. This can create flaky test results where, for example, the EventBus does not reset before the next test function runs. 
This synchronous solution was chosen because it has another benefit for us: by using this more generic solution, we do not need to reset the data store for just the EventBus, we reset the data stores for all objects. Making the test suite …
=> refactor: reduce tearDown flakiness in test suite

Apps/VisionOS/VisionOS.xcodeproj/project.pbxproj, Apps/VisionOS/VisionOS/Storage/AppState.swift, Apps/VisionOS/VisionOS/Storage/Payloads.swift, Apps/VisionOS/VisionOS/Storage/UserDefaultsCodable.swift
This is a PR in a series of PRs to build sample app that runs Identify and Track in VisionPro
The app is built to be an interactive walk through guidance for developers who are integrating Customer.io Swift SDK in their VisioPro apps.
For more context:
In this PR I added storage utilities to persiste/restore the app satate as well as few payloads that will be used for SDK initialization, profile, and events
- Open `VisionOs.xcproject`
- Hit CMD+R to run the project and make sure you have VisionOS simulator installed and selected
---
**Stack**:
- #628
- #627
- #626
- #625
- …
=> docs: [vision-os-sample-app][2/n] App State Storage

Apps/VisionOS/VisionOS.xcodeproj/project.pbxproj, Apps/VisionOS/VisionOS/MainScreen.swift, Apps/VisionOS/VisionOS/Storage/AppState.swift, Apps/VisionOS/VisionOS/ViewUtils/InlineNavigationLink.swift, Apps/VisionOS/VisionOS/ViewUtils/MarkdownTheme.swift, Apps/VisionOS/VisionOS/ViewUtils/SyntaxHighlighting/SplashCodeSyntaxHighlighter.swift, Apps/VisionOS/VisionOS/ViewUtils/SyntaxHighlighting/TextOutputFormat.swift
This is a PR in a series of PRs to build sample app that runs Identify and Track in VisionPro
The app is built to be an interactive walk through guidance for developers who are integrating Customer.io Swift SDK in their VisioPro apps.
For more context:
In this PR I added the InlineNavigationLinks enum and its handling. These enum values represent the screens that will be in the app. It will be used within the markdown content to act as links to navigate to different screens and include some associated values for these screens.
For example:
```
To try this out, see the …
```
=> docs: [vision-os-sample-app][4/n] InlineNavigationLinks

Tests/Common/Service/HttpRequestRunnerTest.swift, Tests/Shared/HttpTest.swift
Part of: https://linear.app/customerio/issue/MBL-164/cdp-branch-flaky-tests-on-ci
An attempt at reducing flakiness of HttpTest tests.
The changes done thus far to try and fix issue:
* Chose a different remote image. Maybe the web server we were using blocks github actions?
* Moved the test out of /Shared/ directory and into /Common/. The test suite assumes that test functions are not written in /Shared/ so maybe that was causing issues?
How did I test this change? 
* Ran test 100 times on local dev machine with success. 
commit-id:0467ebc9
=> test: remove flakiness in HttpTest

Apps/APN-UIKit/APN UIKit/AppDelegate.swift, Sources/DataPipeline/Config/DataPipelineConfigOptions.swift, Sources/DataPipeline/Config/SDKConfigBuilder.swift, Sources/DataPipeline/DataPipelineImplementation.swift, Tests/DataPipeline/Config/SDKConfigBuilderTest.swift
closes: https://linear.app/customerio/issue/MBL-166/update-autotrack-screen-view-config
- Added `autoTrackScreenViews` to `SDKConfigBuilder` so customers can attach screen plugin using config
- Added `autoConfiguredPlugins` to `DataPipelineConfigOptions` so builder can provide finals plugins using convenient config options for customers
=> chore: auto screen tracking plugin using config

Apps/APN-UIKit/NotificationServiceExtension/NotificationService.swift, Apps/CocoaPods-FCM/Rich Push Notification Service Extension/NotificationService.swift, Sources/Common/Util/Log.swift, Sources/Common/autogenerated/AutoDependencyInjection.generated.swift, Sources/DataPipeline/Config/SDKConfigBuilder.swift, Sources/DataPipeline/CustomerIO+Plugins.swift, Sources/DataPipeline/CustomerIO.swift, Sources/DataPipeline/DataPipelineImplementation.swift, Sources/MessagingPush/Config/MessagingPushConfigBuilder.swift, Sources/MessagingPush/Config/MessagingPushConfigOptions.swift, Sources/MessagingPush/MessagingPush.swift, Tests/DataPipeline/APITest.swift, Tests/DataPipeline/Config/SDKConfigBuilderTest.swift, Tests/DataPipeline/Core/UnitTest.swift, Tests/MessagingPush/Config/MessagingPushConfigBuilderTest.swift, Tests/Shared/Core/UnitTestBase.swift
- Fixed singleton logger instance
- Based on changes done in #639, added logger plugin to builder to utilize `autoConfiguredPlugins`
- Removed `setDebugLogsEnabled` extension as I think it was initially added to help `Tracking` module and no longer needed
- Fixed logLevel for NSE
- Updated tests and sample apps
=> chore: logger fixes and improvements

CustomerIOCommon.podspec, CustomerIOMessagingInApp.podspec, CustomerIOMessagingPush.podspec, CustomerIOMessagingPushAPN.podspec, CustomerIOMessagingPushFCM.podspec, CustomerIOTracking.podspec
Fixes: https://linear.app/customerio/issue/MBL-180/[bug]-resolve-md-file-causing-compilation-issues-for-ios-customers
Customers experience compilation errors in their iOS/RN/Flutter/Expo apps due to customer's apps trying to parse .md files that are bundled with our SDK in production releases.
In a recent release of our SDK, we wrote a new md file for internal documentation of the code: https://github.com/customerio/customerio-ios/blob/f50e5b81dd9896e1d76d5dd27fe94709f176dbd1/Sources/MessagingPush/UserNotificationsFramework/README.md. This file is being included in the source code that is shipped in production releases of our iOS SDK.
This change filters out .md files in cocoapods deployments.
Notes:
* From reviewing other SDKs who also encountered this error, the SDKs were only modifying …
=> fix: do not bundle .md files in cocoapods deployments

Tests/Common/Module/ModuleTopLevelObjectTest.swift, Tests/MessagingPush/PushHandling/PushEventHandlerProxyTest.swift, Tests/Shared/Core/UnitTestBase.swift
Part of: https://linear.app/customerio/issue/MBL-164/cdp-branch-flaky-tests-on-ci
There is a set of flaky tests that all have 1 thing in common: They are the only tests that call the functions `runOnBackground` or `runOnMain`. 
From my own personal experience and research online, tests that use GCD can have unexpected/flaky results, especially on simulators. Recent versions of Xcode or Swift may also have changed the behavior to become flaky. 
This commit changes to using swift concurrency instead of GCD to run test functions on background threads. We hope that all of these tests pass on the CI with no more flaky results. 
commit-id:cc25358b
=> test: fix flaky tests that run code on another thread

Sources/DataPipeline/DataPipelineImplementation.swift, Sources/Migration/DataPipelineMigrationAssistant.swift
Based on sample app testing it was found that the device attributes are not passed in properties parameters but `context.device`. This PR fixes the issue! 
=> fix: add attributes to properties 

Sources/MessagingPush/Config/MessagingPushConfigOptions.swift, Sources/MessagingPush/MessagingPush.swift, Sources/MessagingPush/MessagingPushInstance.swift, Sources/MessagingPush/RichPush/RichPushHttpClient.swift, Sources/MessagingPush/autogenerated/AutoMockable.generated.swift, Sources/MessagingPushAPN/MessagingPushAPN.swift, Sources/MessagingPushFCM/MessagingPushFCM.swift, Tests/MessagingPushAPN/APITest.swift, Tests/MessagingPushFCM/APITest.swift
The PR fixes an issue where `RichPushHttpClient` was trying to access push module config before it was set as it is initialized with `MessagingPushImplementation` due to changes made in #560 
- Reverted push module to be static because it matches with `DataPipeline` module implementation
- Event though we could update `RichPushHttpClient` to use config from implementation, but this appears to be error-prone and has a chance of breaking things in future. So we have reverted back to use static module config directly.
=> chore: revert push module config to use static

Sources/DataPipeline/Config/SDKConfigBuilder.swift, Sources/DataPipeline/CustomerIO+Segment.swift, Tests/DataPipeline/APITest.swift
closes: https://linear.app/customerio/issue/MBL-181/remove-config-settings-from-public-api
- Removed following public apis as discussed in the ticket
- `operatingMode`
- `flushInterval`
- `flushAt`
- `flushPolicies`
- `traits`
- `version`
- `settings`
- `manuallyEnableDestination`
- `openURL`
- Fixed API tests
=> chore: remove unwanted public apis

CustomerIODataPipelines.podspec, Package.swift
Part of: https://linear.app/customerio/issue/MBL-167/segment-dependency-currently-pointing-to-main-branch
In the iOS SDK today, with the Segment CDP SDK, we are currently specifying the version of the segment SDK as "main branch". Using a git branch as the version of a dependency poses risks, potentially leading to difficulties for customers during SDK updates and app compilation, increasing the chance of crashes or compilation issues.
This change uses a hard-coded git commit. The git commit used is the latest commit on the "main" branch.
There are pros and cons to using a git commit as the version, as specified in the ticket description. We can change to a different version such as a git tag in the future.
commit-id:45c2d17e
=> fix: use git commit instead of git branch for segment dependency

Sources/DataPipeline/DataPipelineImplementation.swift
Since we don't have much context on whether the users will be relying on `id` or `email` while migrating their events from tracking to CDP, we need to remove it and rely on the `userId` attribute being added. 
I have verified these manually and test cases are going to follow later and will be handled by Amans PR.
=> fix: journey id in migration payload

Sources/DataPipeline/CustomerIO+Events.swift
Until the group traits format is sorted out, we have decided to hide the group APIs.
=> chore: hide object APIs for initial release

Package.swift
Resolve error, "Failed to resolve dependencies Dependencies could not be resolved because root depends on 'customerio-ios' 3.0.0..<4.0.0. 'customerio-ios' >= 3.0.0 cannot be used because no versions of 'customerio-ios' match the requirement and package is required using a stable-version but depends on an unstable-version package"
=> fix: install 3.0 with Swift Package Manager from Xcode

Apps/VisionOS/VisionOS.xcodeproj/project.pbxproj, Apps/VisionOS/VisionOS/APIViews/SDKInitializationView.swift, Apps/VisionOS/VisionOS/MainScreen.swift
This is a PR in a series of PRs to build sample app that runs Identify and Track in VisionPro
For more context:
This PR introduces the SDK Initialization view where that demonstrates the usage of the `initialize` API
- `CustomerIO.initialize` is called with the correct value when hitting "Initialize" button
- App state updates to reflect the SDK has been initialized
https://github.com/customerio/customerio-ios/assets/142905621/0e9550fa-2d54-450c-a92d-5a6b92e4684a
--
- #668 
- #667 
- #666 
- #665 👈
- #664   
- #663
=> docs: [vision-os-sample-app][7/n] SDK Initialization view

.github/workflows/build-sample-apps.yml, Apps/.gitignore, Apps/fastlane/Fastfile
Part of: https://linear.app/customerio/issue/MBL-155/track-the-binary-size-of-our-ios-sdk-upon-every-release
Modify the CI to print the binary size of the SDK files in a compiled sample app.
To view the SDK size report, you must view the CI logs. This was a decision the team made as the initial scope of the feature.
commit-id:7c521be9
=> ci: print the binary size of the SDK

Sources/Common/Service/UserAgentUtil.swift, Tests/Common/Service/UserAgentUtilTest.swift
The user agent is currently hard-coded to use iOS as the os name. I changed it to pick the value from the `deviceInfo` object and default to `iOS`
=> chore: Use actual os name for the user agent

Apps/VisionOS/VisionOS/AppDelegate.swift, Apps/VisionOS/VisionOS/MainScreen.swift
- Updates the success message for the identify call
- Add an inline comment in the AppDelegate for simple instruction to set the CDP API Key in the code instead of the UI
=> docs: VisionOS sample app minor UI tweak

Sources/DataPipeline/DataPipelineImplementation.swift, Sources/Migration/DataPipelineMigrationAssistant.swift, Tests/DataPipeline/DataPipelineImplementation+MigrationTests.swift, Tests/Migration/DataPipelineMigrationAssistantTests.swift
close: https://linear.app/customerio/issue/MBL-178/increase-test-coverage-of-track-bq-migration
Two of migration files were missing/had insufficient test coverage. The ask of the ticket above was to increase the test coverage to increase confidence in the migration module. Hence, this PR caters the following:
- write test cases of the uncovered methods in MigrationAssistant
- write test cases of the uncovered methods in DataPipelineImplementation
MigrationAssistant's updated coverage - 100% (previously 50%)
DataPipelineImplementation's updated coverage - 90.64% (previously 61.54%)
=> test: migration test cases covering all task types

Sources/MessagingPush/Config/MessagingPushConfigBuilder.swift, Sources/MessagingPush/MessagingPush.swift, Sources/MessagingPushAPN/MessagingPushAPN.swift, Sources/MessagingPushFCM/MessagingPushFCM.swift
We have APIs, mainly for push, that's restricted to iOS 13.0 and above. They can safely be enabled for VisionOS 1.0 as well.
Add NSE to a VisionOS app and make sure it builds and works as expected when using rich push
=> chore: Support visionOS 1.0

Sources/DataPipeline/Plugins/Context.swift
The push notification logic won't work if the device.type isn't ios. This PR is a mitigation for now to enable push notifications on VisionOS till we have a better handling on the backend
=> chore: Overriding device.type for VisionOS

.github/workflows/build-sample-apps.yml
Part of: https://linear.app/customerio/issue/MBL-155/track-the-binary-size-of-our-ios-sdk-upon-every-release
In order for us to perform SDK binary size changes in each PR, each PR needs to know the SDK binary size of the main branch.
This commit sets up the CI to cache sample app builds for the main branch. In future commits, PR builds can then download this cache and generate SDK binary size comparison reports.
=> ci: cache sample app builds on the main branch

CustomerIOMessagingInApp.podspec, CustomerIOMessagingPushAPN.podspec, CustomerIOMessagingPushFCM.podspec, CustomerIOTracking.podspec, Package.swift, Sources/MessagingInApp/Resources/PrivacyInfo.xcprivacy, Sources/MessagingPushAPN/Resources/PrivacyInfo.xcprivacy, Sources/MessagingPushFCM/Resources/PrivacyInfo.xcprivacy, Sources/Tracking/Resources/PrivacyInfo.xcprivacy
Closes: https://linear.app/customerio/issue/MBL-187/update-values-based-on-linear-doc
Part of: https://linear.app/customerio/issue/MBL-189/release-ios
Create privacy manifest files for all target modules that customers could decide to install in an app. Update package manager config files to include these new resource files.
Testing criteria CocoaPods:
* `pod update`, opened app in xcode
* Verified that in 'Pods' project settings, there are new targets added for each module (example: `CustomerIODataPipelines-CustomerIODataPipelines_Privacy`). I then verified in each of the `_Privacy targets > Build phases > compile sources` list, the privacy manifest files were listed and they resource to a valid path.
* App compiled without any new warnings.
Testing criteria SPM:
* Opened sample app in …
=> feat: privacy manifest files

Sources/Migration/DataPipelineMigrationAssistant.swift, Tests/Migration/DataPipelineMigrationAssistantTests.swift
As a continuation of the PR, https://github.com/customerio/customerio-ios/pull/702, this commit safely unwraps all of the optional values in the Track BQ to CDP migration code.
I do not expect that register device attributes string to be null because the attributes string will contain at least the device token. In PR discussion (https://github.com/customerio/customerio-ios/pull/702#discussion_r1567022655), we were not sure a bug could happen from this code but we still wanted to safety unwrap the optional to avoid any possible crashes.
commit-id:24cb8fd5
---
**Stack**:
- #704 ⬅
- #702
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> refactor: safely unwrap register device BQ tasks in migration code

.github/workflows/build-sample-apps.yml, Apps/APN-UIKit/APN UIKit.xcodeproj/project.pbxproj
Part of: https://linear.app/customerio/issue/MBL-155/track-the-binary-size-of-our-ios-sdk-upon-every-release
In the previous commit, there was an error when the CI tried to create a PR comment with all of the SDK size reports in it. The error says it's because the PR comment hit a maximum character limit. To fix this, I removed one of the SDK size reports from the PR comment - the SDK size report that includes dependencies. I chose this solution because this SDK size report is the biggest report there is and also because we currently don't have any metrics tracking our SDK size including dependencies.
commit-id:6c6d1d99
---
**Stack**:
- #709
- #700 ⬅
- #699
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have …
=> ci: fix PR report comment hitting max limit of characters

CustomerIODataPipelines.podspec, Package.swift
in the new Segment release, the internal dependencies (sovran, JSON encoder) versions are fixed.
=> fix: update segment internal SPM dependencies with fixed version

.github/workflows/deploy-sdk.yml
The CI is currently failing to generate SDK size reports during releases of the SDK. This is caused due to a recent configuration change in the GitHub Action that generates these reports. The configuration was not updated in all workflows that use this action.
This commit provides the latest configuration of the Action to get the CI generating SDK size reports again during releases.
=> ci: fix CI generating SDK size reports during deployments

.github/actions/generate-sdk-size-report/action.yml
I noticed in a recent PR I opened that the CI was not able to download the latest main branch sample app cached build. After scrolling through the long logs, I noticed an action was not called with the correct inputs. Unfortunately, it seems like if an action receives incorrect inputs, it does not throw errors as I expected but it instead continues running.
=> ci: fix main branch sample app caching

Sources/DataPipeline/CustomerIO+Segment.swift
removing Segment mentions not to confuse customers.
=> chore: cleanup public APIs

CustomerIODataPipelines.podspec, Package.swift
closes: https://github.com/customerio/customerio-ios/issues/721
Remove reliance on `WWebview`, which can cause crash at times during development.
=> fix: crash on emulator while development

Sources/MessagingPush/PushHandling/iOSPushEventListener.swift
The push event listener has several early exits that aren't logged. Which would make it harder to understand what's happening if something causes and early exit unexpectedly.
=> chore: Adding debug logs for the push event listener

Sources/MessagingInApp/MessagingInAppImplementation.swift, Tests/DataPipeline/DataPipelineCompatibilityTests.swift, Tests/MessagingInApp/MessagingInAppImplementationTest.swift
closes: https://linear.app/customerio/issue/INAPP-12554/in-app-tracked-responses-does-not-match-clicked-metrics-in-env-154794
updates keys of `actionValue` and `actionName` in properties, for `Report Delivery Event` event.
=> fix: action tracking for in-app

Sources/MessagingInApp/Gist/Gist.swift, Sources/MessagingInApp/Gist/Managers/InlineMessageManager.swift, Sources/MessagingInApp/Gist/Managers/MessageManager.swift, Sources/MessagingInApp/Gist/Managers/ModalMessageManager.swift, Sources/MessagingInApp/Gist/Managers/Models/Message.swift, Sources/MessagingInApp/Views/InAppMessageView.swift, Sources/MessagingInApp/autogenerated/AutoMockable.generated.swift, Tests/MessagingInApp/Views/InAppMessageViewTest.swift
Part of: https://linear.app/customerio/issue/MBL-310/create-a-uikit-uiview-that-displays-an-inline-in-app-message-sent-from
Create a WebView to display inline in-app message and display in the Inline UIView. To do this, we can re-use a lot of the same logic that Modal messages use to create WebViews and display them.
Testing:
There are some automated tests added in this commit.
Reviewer notes:
This commit will not show an in-app message if you were to add it to a sample app. Autolayout constraints need to be added to have Views resize and that will come in a future commit.
---
**Stack**:
- #720
- #718
- #717 ⬅
- #716
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> chore: get WebView for inline message and add to Inline View to display

Sources/MessagingPush/PushHandling/PushEventHandlerProxy.swift, Sources/MessagingPush/PushHandling/iOSPushEventListener.swift, Tests/MessagingPush/PushHandling/AutomaticPushClickedIntegrationTest.swift
Part of: https://linear.app/customerio/issue/MBL-364/[bug]-push-notifications-not-showing-while-app-in-foreground-on-ios
When a push event occurs in an iOS app (such as determining if a push should be shown while app in foreground), the CIO SDK forwards that event to all 3rd party SDKs in the app. Some 3rd party SDKs handle these push events by also forwarding those events back to the CIO SDK. This has resulted in push handling in an app to not behave as expected. 
See the ticket and included tests in this PR to learn more about the implementations of these 3rd party SDKs and how we handle them. 
Testing:
* Added automated tests to this PR reproducing each of the problem scenarios I have encountered during QA. 
* QA regression tested push features in iOS, RN, Flutter, and Expo. 
Note to …
=> fix: 3rd party SDK compatibility when SDK forwards push events back to us

Sources/Common/Type/DoNotTrackAutomaticScreenViewEvent.swift, Sources/DataPipeline/Plugins/AutoTrackingScreenViews.swift, Sources/MessagingInApp/Gist/Gist.swift, Sources/MessagingInApp/Gist/Views/GistModalViewController.swift, Tests/DataPipeline/DataPipelineImplementation+ScreenViewsTest.swift
Part of: https://linear.app/customerio/issue/MBL-355/ios-fix-in-app-message-displayed-on-wrong-page
There is a scenario where a modal message can be displayed on the wrong screen due to a timing issue. Although the time window where this could happen is small, it was encountered during QA testing.
Test case to reproduce:
* In-app message with page rule "Dashboard" sent to device. User on "Dashboard" screen. In-app message begins to render.
* Similar to what is explained [here](https://customerio.slack.com/archives/C06H7MMLH6C/p1716391939537599), if the user of the app clicks a button to begin navigating to another screen in the app and the modal message finishes rendering during the screen transition animation, the modal will be displayed and will remain displayed after the animation is …
=> chore: improve reliability dismissing modal messages on page rule change

Sources/MessagingInApp/Gist/Gist.swift, Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift, Sources/MessagingInApp/Gist/Managers/Models/Message.swift, Tests/MessagingInApp/Extensions/GistExtensions.swift, Tests/MessagingInApp/Gist/Managers/Models/MessageTest.swift, Tests/MessagingInApp/MessagingInAppIntegrationTests.swift
* PR #740: `levi/compare-regex-page-rules` ➔ `levi/instantly-dismiss-modals`
* PR #739: `levi/instantly-dismiss-modals` ➔ `levi/ignore-cio-autoscreenviews`
* PR #732: `levi/ignore-cio-autoscreenviews` ➔ `levi/inapp-strict-pagerules`
* PR #731: `levi/inapp-strict-pagerules` ➔ `main`
Part of: https://linear.app/customerio/issue/MBL-355/ios-fix-in-app-message-displayed-on-wrong-page
Because page rules can contain regex, you could change screens in the app and the currently shown message can still match that screen. Do not cancel if the message matches the new route.
Testing
* Added automated tests.
=> chore: do not dismiss modal when page route changed and regex pattern matches

Sources/MessagingPush/PushHandling/PushEventHandlerProxy.swift, Sources/MessagingPush/UserNotificationsFramework/Wrappers.swift
Part of: https://linear.app/customerio/issue/MBL-383/[bug]-customer-unable-to-handle-push-notification-event-on-ios-with
To help customers faster, our debug logs need an improvement with the push event handling feature. This PR makes the following improvements:
```
// Example log before this PR
Sending push notification, <title of push>, event to: UNUserNotificationCenterDelegateWrapper. Customer.io SDK will wait for async completion handler to be called...
// Example log after this PR
Sending push notification, <title of push>, will display event to: Cio.NotificationCenterDelegateWrapper(<APN_UIKit.AppDelegate: 0x303f88c80>)). Customer.io SDK will wait for async completion handler to be called...
```
These logs are improved in 2 ways:
1. The 3rd party push click handler is described …
=> chore: improve logs when forwarding push events to 3rd part handlers

Sources/MessagingPush/PushHandling/PushEventHandler.swift, Sources/MessagingPush/PushHandling/PushEventHandlerProxy.swift, Sources/MessagingPush/PushHandling/iOSPushEventListener.swift, Sources/MessagingPush/UserNotificationsFramework/Wrappers.swift, Sources/MessagingPush/autogenerated/AutoMockable.generated.swift, Tests/MessagingPush/IntegrationTest.swift, Tests/MessagingPush/PushHandling/AutomaticPushClickedIntegrationTest.swift, Tests/MessagingPush/PushHandling/AutomaticPushDeliveredAppInForegroundTest.swift, Tests/MessagingPush/PushHandling/PushEventHandlerProxyTest.swift
https://linear.app/customerio/issue/MBL-383/[bug]-customer-unable-to-handle-push-notification-event-on-ios-with
At runtime when `PushEventHandlerProxy.addPushEventHandler` is called, the given push event handler will overrwrite any previously added push event handlers. This results in the SDK only being aware of 1 push event handler even if the iOS app has N number installed.
Testing
* In Flutter sample app, install CIO SDK, FlutterFire, and set `UNNotificationCenterDelegate.current().delegate = self` in `AppDelegate` for the host app to also handle pushes. This reproduces the bug because we now have at least 2 other push click handlers besides the CIO SDK installed. Set a Xcode breakpoint in `PushEventHandlerProxy.addPushEventHandler` and check what dictionary key is generated. 
* I …
=> fix: differentiate every push event handler installed in app

.github/actions/setup-ios/action.yml
I've noticed that our test suite has become flaky and now takes an hour to run instead of the usual 5 minutes. This started with the release of Xcode 15.4. Our CI is set to use the latest major version, so it switched to 15.4 automatically. Other developers online have reported similar issues with 15.4. Reverting to Xcode 15.3, which was stable for us, seems like a good workaround to stabilize our CI.
=> ci: fix flaky test suite runs on CI

Sources/MessagingInApp/Gist/Gist.swift, Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift, Sources/MessagingInApp/Gist/Managers/QueueManager.swift, Tests/MessagingInApp/MessagingInAppIntegrationTests.swift
* PR #749: `levi/cache-inapp-response-clear-on-logout` ➔ `levi/cache-inapp-responses-integration-tests`
* PR #748: `levi/cache-inapp-responses-integration-tests` ➔ `levi/cache-inapp-response-test-setup`
* PR #747: `levi/cache-inapp-response-test-setup` ➔ `levi/cache-inapp-responses-at-network-level`
* PR #746: `levi/cache-inapp-responses-at-network-level` ➔ `main`
Part of: https://linear.app/customerio/issue/MBL-373/[bug]-in-app-messages-do-not-show-on-ios-if-page-rules-are-enabled-and
When SDK is logged out, clear the in-app network cache to prevent displaying messages to the wrong Journeys profile.
Testing:
* Automated tests added.
* QA test case in the linear ticket passed in sample apps.
Reviewer notes:
* This implementation was chosen to match the behavior of Android 3.11.0
=> chore: clear in-app message cache on sdk logout

Sources/MessagingPush/PushHandling/PushEventHandlerProxy.swift, Sources/MessagingPush/UserNotificationsFramework/Wrappers.swift
Part of: https://linear.app/customerio/issue/MBL-383/[bug]-customer-unable-to-handle-push-notification-event-on-ios-with
(identical to this PR: https://github.com/customerio/customerio-ios/pull/745, but this points to v3 branch)
To help customers faster, our debug logs need an improvement with the push event handling feature. This PR makes the following improvements:
```
// Example log before this PR
Sending push notification, <title of push>, event to: UNUserNotificationCenterDelegateWrapper. Customer.io SDK will wait for async completion handler to be called...
// Example log after this PR
Sending push notification, <title of push>, will display event to: Cio.NotificationCenterDelegateWrapper(<APN_UIKit.AppDelegate: 0x303f88c80>)). Customer.io SDK will wait for async completion handler …
```
=> chore: improve logs when forwarding push events to 3rd party handlers

Apps/APN-UIKit/APN UIKit/Base.lproj/Main.storyboard, Apps/APN-UIKit/APN UIKit/View/Customisation/CustomDataViewController.swift, Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift, Tests/MessagingInApp/Gist/Managers/MessageQueueManagerTest.swift
[Implement page rules with inline messages](https://linear.app/customerio/issue/MBL-314/implement-page-rules-with-inline-messages)
As a marketer I want some inline in-app messages to only be displayed on certain screens of my app. The in-app message does not display inline on the screen that was set in page rules.
For QA, there are three inline views in UIKit Sample app. 
2 on the dashboard screen - `dashboard-announcement` and `dashboard-announcement-code`
1 on custom attributes screen -  `custom-screen`
To avoid any confusion, since same controller `CustomDataViewController` is used for Custom Attributes, Device Attributes,  Profile Attributes so if an in-app message is targeted for element Id `custom-screen` it will show every time a user visits any of the above screens. 
**Steps to …
=> feat: add page rule for inline inapp messages

Sources/MessagingInApp/Views/InAppMessageView.swift
https://linear.app/customerio/issue/MBL-313/after-close-action-pressed-replace-in-app-message-with-next-in-queue
As a marketer, I want to display another in-app message inline when close button pressed so I can rotate between multiple in-app messages.
When you click close button and a new inline message needs to be displayed, it could take a couple seconds for renderer response. The transition between messages should be seamless and not disrupt the user experience.
When the close button is pressed...
1. Fade out the currently shown in-app message while also fading in an iOS [Activity Indicator](https://developer.apple.com/design/human-interface-guidelines/progress-indicators). The height of the View remains the same as what the old in-app message's height was. 
2. Show the activity …
=> chore: add animations and activity indicator while rendering next message

Tests/MessagingInApp/Core/IntegrationTest.swift, Tests/MessagingInApp/EngineWeb/EngineWebProviderStub.swift, Tests/MessagingInApp/MessagingInAppIntegrationTests.swift, Tests/MessagingInApp/Views/InAppMessageViewTest.swift
Follow-up to resolve [this PR suggestion](https://github.com/customerio/customerio-ios/pull/756/files#r1661294641). 
The `EngineWebProviderStub` allows us to mock events that happen to in-app message WebViews in our tests. The previous stub only allowed us to call mocks on 1 instance of a inline View object. The new stub allows us to call mocks on 2+ separate instances. 
This PR is a refactor to the test suite that uses the new `EngineWebProviderStub` instance. This PR should not modify any logic or test functions. It should be purely a refactor.
=> test: refactor tests to use 1 enginewebproviderstub

Sources/Common/Communication/EventBusHandler.swift, Sources/MessagingInApp/MessagingInAppImplementation.swift, Tests/MessagingInApp/Core/IntegrationTest.swift, Tests/MessagingInApp/EngineWeb/EngineWebProviderStub.swift, Tests/MessagingInApp/Views/InAppMessageViewTest.swift, Tests/Shared/Core/UnitTestBase.swift
Linear ticket : https://linear.app/customerio/issue/MBL-331/track-opened-and-clicked-metrics
As a marketer, I want to see how effective my inline messages so that I can make better messaging campaigns in the future. I care about how many messages were shown and how many were acted upon (clicked).
This PR adds unit test cases for tracking the effectiveness of inline in-app messages. The tests ensure that metrics for `opened` and `clicked` events are accurately recorded. The primary focus is to prevent duplicate event tracking, which is critical for inline messages due to their potential to be displayed and interacted with multiple times within the app. The tests cover scenarios to verify that:
1.	Inline messages report “opened” when displayed.
2.	Inline messages report “clicked” when an …
=> test: track opened and clicked metrics

Tests/MessagingInApp/Core/IntegrationTest.swift, Tests/MessagingInApp/Extensions/GistExtensions.swift, Tests/MessagingInApp/Views/InAppMessageViewTest.swift
Automated tests for: https://linear.app/customerio/issue/MBL-329/after-inline-view-shown-determine-if-it-should-show-again-or-not
Given the acceptance criteria in the ticket and the description of persistent and non-persistent messages, I wrote automated test functions for the feature. 
I tried to write automated tests for all test cases that we would use to manually QA test this feature. If you believe a test case is missing, please call it out.
=> test: persistent and non-persistent messages

Sources/Common/Util/JsonAdapter.swift, Sources/MessagingInApp/Views/InAppMessageView.swift, Tests/MessagingInApp/Core/IntegrationTest.swift, Tests/MessagingInApp/Extensions/GistExtensions.swift, Tests/MessagingInApp/Views/InAppMessageViewTest.swift, Tests/Shared/Core/UnitTestBase.swift
Unblocks writing tests for ticket: https://linear.app/customerio/issue/MBL-329/
If the inline View tests were integration tests instead of unit tests, we would be able to write more automated tests and reduce false positives in our test functions. 
This change makes the following modifications to the inline in-app test suite: 
* Only mocking done is mocking the HTTP response when fetching messages. 
* Be able to mock HTTP requests with any given `[Message]` array.
=> test: convert inline in-app View tests to integration tests

Sources/Common/Util/JsonAdapter.swift, Sources/MessagingInApp/Gist/Gist.swift, Sources/MessagingInApp/Gist/Managers/InlineMessageManager.swift, Sources/MessagingInApp/Gist/Managers/MessageManager.swift, Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift, Sources/MessagingInApp/Gist/Managers/ModalMessageManager.swift, Sources/MessagingInApp/Views/InAppMessageView.swift, Tests/MessagingInApp/Core/IntegrationTest.swift, Tests/MessagingInApp/Extensions/GistExtensions.swift, Tests/MessagingInApp/MessagingInAppImplementationTest.swift, Tests/MessagingInApp/Views/InAppMessageViewTest.swift, Tests/Shared/Core/UnitTestBase.swift
https://linear.app/customerio/issue/MBL-329/after-inline-view-shown-determine-if-it-should-show-again-or-not
As a marketer, I want to customize an inline in-app message to be shown only once or shown multiple times. 
According [to the in-app docs](https://customer.io/docs/journeys/send-in-app-message/#persist-message), persistent messages are defined as: 
> By default, in-app messages only show once—the message disappears after the customer clicks, taps, or refreshes the page. You can check the Persist Message option to show your message across multiple sessions and page views. Persisted messages continue being displayed until the expiration date or until the customer clicks Close or the icon. Make sure your messages include a Close button or an icon so that customers can permanently …
=> feat: persistent and non-persistent inline in-app messages

Tests/MessagingInApp/Core/IntegrationTest.swift, Tests/MessagingInApp/Views/InAppMessageViewTest.swift
Automated tests are not compiling on `feature/inline-inapp` branch after latest set of PRs that I merged. I believe this happened because of a merge conflict I resolved in 1 of the PRs but didn't propagate that merge up the PR stack. 
I fixed those issues and got tests passing again.
=> test: fix inline View tests 

Apps/CocoaPods-FCM/src/View/CustomEventView.swift, Apps/CocoaPods-FCM/src/View/DashboardView.swift, Sources/MessagingInApp/Views/SwiftUIInline.swift, Tests/MessagingInApp/Core/IntegrationTest.swift, Tests/MessagingInApp/Views/InAppMessageViewTest.swift
While doing QA testing on SwiftUI inline View, I noticed a bug: 
* On Dashboard screen, display an inline message. 
* Rotate screen to landscape. Expect that the inline View expands it's width to the new larger width. 
* Rotate screen back to portrait. Expect the inline View shrinks it's width back to the smaller width. Actual behavior, the inline View's width stays to what it was in landscape mode. 
I tested in both UIKit and SwiftUI sample apps. This behavior *only* happened in the SwiftUI app. 
I set a breakpoint in `GistInlineMessageUIView.intrinsicContentSize` and noticed that in the SwiftUI app, when you rotate back to portait orientation, `intrinsicContentSize` does not get called. But in UIKit app, it gets called every time that you rotate the screen. 
By use of …
=> fix: rotate screen and expect inline View width to change

Apps/CocoaPods-FCM/src/View/CustomEventView.swift, Apps/CocoaPods-FCM/src/View/DashboardView.swift, Sources/MessagingInApp/Views/SwiftUIInline.swift, Tests/MessagingInApp/Core/IntegrationTest.swift, Tests/MessagingInApp/Views/InAppMessageViewTest.swift
Now that the SwiftUI implementation for inline in-app is complete, I decided to check and see if setting the `frame()` on the SwiftUI inline View is required or not anymore. Previously, we discussed that it might be needed for customers to add it to their app. 
I removed the `frame()` call from sample app, tested it, and the inline View is behaving as expected where the width of the inline View equals the width of the parent container. Therefore, I do not think that setting the frame is expected anymore. I think this is the ideal scenario - Customers *can* set the frame, but it is not a requirement.
This PR removes the `.frame()` call that has no effect on the sample app. Also, our SwiftUI inline docs do not mention that using `.frame()` is required so this change will make our sample app …
=> docs: remove unneeded code in SwiftUI sample app

CustomerIODataPipelines.podspec, Package.swift
Resolves: https://github.com/customerio/customerio-ios/issues/790 
iOS developers who want to use tools such as Tuist to generate xcode projects are currently experiencing an error when resolving the CIO iOS SDK via SPM.
See [this PR for the full details of the problem and solution](https://github.com/customerio/cdp-analytics-swift/pull/7). 
In order for customers to be able to install the iOS SDK via tuist, the iOS SDK's SPM manifest file must point to the correct version of `CioAnalytics` that includes the bug fix. 
After this PR gets deployed, customers should be able to install the iOS SDK via tuist on the latest version. 
Installed this git branch in SPM and Cocoapods sample apps. Verified that the correct source code was downloaded and that the apps compile successfully. 
I am also …
=> fix: tuist users not able to install CIO iOS SDK SPM manifest issue

Sources/MessagingInApp/Gist/EngineWeb/EngineWeb.swift, Sources/MessagingInApp/Gist/Gist.swift, Sources/MessagingInApp/Gist/Managers/MessageManager.swift, Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift, Sources/MessagingInApp/Gist/Managers/ModalViewManager.swift, Sources/MessagingInApp/Gist/Managers/UserManager.swift, Sources/MessagingInApp/MessagingInAppImplementation.swift
part of [MBL-483](https://linear.app/customerio/issue/MBL-483/add-logs-that-would-help-troubleshoot-pocket-prep-issue)
- Fetch in-app messages from remote whenever a profile is identified to speed up first message display and adjust the polling interval as received
- Improved logging
- [Slack discussion about removing in-app message preloading](https://customerio.slack.com/archives/C036FTE6UJ0/p1721046751535539)
=> feat: fetch in-app messages on new profile identification

Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift
part of [MBL-483](https://linear.app/customerio/issue/MBL-483/add-logs-that-would-help-troubleshoot-pocket-prep-issue)
- Fetch in-app messages from remote on `DispatchQueue.main` explicitly
=> fix: fetch remote messages on main queue

.github/actions/generate-sdk-size-report/action.yml, .github/actions/main-sample-app-build/action.yml
closes: [MBL-510](https://linear.app/customerio/issue/MBL-510/[ios]-fix-sdk-binary-size-on-ci)
SDK binary size task started failing because sample app build from `main` branch could not be restored from the cache. This PR refactors cache handling logic for `main` build in SDK size action and introduces more streamlined approach to check for cache hits and handle fallback builds when the cache is unavailable.
- Introduced `cache_hit` variable to store cache-hit status and use it throughout the workflow
- Simplified conditionals that depend on the cache-hit status, reducing redundant checks
- Ensured `main` build is cached correctly, whether from a restored cache or a newly triggered fallback build
=> ci: sdk binary size main build cache hit

Sources/MessagingInApp/Extensions/GistExtensions.swift, Sources/MessagingInApp/Gist/Managers/MessageManager.swift, Sources/MessagingInApp/State/InAppMessageAction.swift, Sources/MessagingInApp/State/InAppMessageMiddleware.swift, Sources/MessagingInApp/State/InAppMessageReducer.swift
part of [MBL-480](https://linear.app/customerio/issue/MBL-480/update-in-app-messaging-module-using-state-management-in-ios)
- Ignored embedded (inline) in-app messages when filtering messages to be displayed, as inline support is not available in this branch
- Updated `Message` and `GistProperties` classes for improved logging and debugging
=> chore: ignore inline in-app messages

CustomerIOMessagingInApp.podspec, Package.swift, Sources/MessagingInApp/State/Aliases.swift, Sources/MessagingInApp/State/Core/Assertions.swift, Sources/MessagingInApp/State/Core/Middleware.swift, Sources/MessagingInApp/State/Core/Reducer.swift, Sources/MessagingInApp/State/Core/Store.swift, Sources/MessagingInApp/State/Core/StoreSubscriber.swift, Sources/MessagingInApp/State/Core/Subscription.swift, Sources/MessagingInApp/State/Core/Synchronized.swift, Sources/MessagingInApp/State/InAppMessageAction.swift, Sources/MessagingInApp/State/InAppMessageMiddleware.swift, Sources/MessagingInApp/State/InAppMessageReducer.swift, Sources/MessagingInApp/State/InAppMessageStore.swift
part of [MBL-480](https://linear.app/customerio/issue/MBL-480/update-in-app-messaging-module-using-state-management-in-ios)
- Removed `ReSwift` dependency so that pods can work without any workarounds
- Moved middleware to `InAppMessageMiddleware` file as private implementation to avoid naming conflicts in other files
- Simplified reducer and middleware as action type is `InAppMessageAction` everywhere
- Copied following files from [`ReSwift`](https://github.com/ReSwift/ReSwift/tree/11f0a2e4965487c8d1f1dd1cffc59e39ef3f2666) and modified them as needed to maintain the custom store functionality:
- `Assertions`
- `Middleware`
- `Reducer`
- `Store`
- `StoreSubscriber`
- `Subscription`
- `Synchronized`
=> refactor: custom store implementation

Sources/MessagingInApp/State/InAppMessageManager.swift, Tests/MessagingInApp/Core/IntegrationTest.swift, Tests/MessagingInApp/EngineWeb/EngineWebProviderStub.swift, Tests/MessagingInApp/Extensions/GistExtensions.swift, Tests/MessagingInApp/State/InAppMessageStateTests.swift
helps: [MBL-501](https://linear.app/customerio/issue/MBL-501/add-tests)
changes:
- Updated to helper methods for message
- Changes in test utilities WRT to new classes
- Added tests for state changes
It doesn't contain module tests, which would be failing.
=> test: added tests for state

CustomerIOMessagingPushFCM.podspec, Package.swift
Linear ticket: https://linear.app/customerio/issue/MBL-472/firebase-1100-support
Customers are currently facing issues when upgrading to Firebase's latest version, 11.2. They want to use the latest version of the dependency, but our package restricts usage to versions up to 11.0, preventing them from installing higher versions.
Update the version range and test if the app successfully upgrades to the latest Firebase version while using our SDK.
Updated the range to >8.7.0 <12.0.0 and tested on UIKit and CocoaPod sample apps. There are no major breaking changes as per the [official Firebase document](https://firebase.google.com/support/release-notes/ios#11.0.0) that affects our SDK.
------
Complete each step to get your pull request merged in. [Learn more about the workflow this project …
=> chore: firebase version update

Sources/Common/Util/Log.swift, Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/MessagingInApp/Config/MessagingInAppConfigBuilder.swift, Tests/Common/Type/RegionTest.swift, Tests/MessagingInApp/Config/MessagingInAppConfigBuilderTest.swift
part of: [MBL-538](https://linear.app/customerio/issue/MBL-538/add-feature-for-inapp-messages-in-ios-rn), [MBL-546](https://linear.app/customerio/issue/MBL-546/inapp-event-listeners-ios-and-android-rn)
- Updated `Logger` class to allow setting log dispatcher for intercepting logs, ensuring only one logger instance and matching Android behavior
- Updated `MessagingInAppConfigBuilder` to meet React Native package expectations and provide clearer error explanations
- Updated tests for `Region` and `MessagingInAppConfigBuilder` to validate changes
=> chore: in-app messaging config from dictionary

Sources/Common/Service/UserAgentUtil.swift, Sources/Common/Util/SdkClient.swift, Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/MessagingPush/MessagingPushImplementation.swift, Sources/MessagingPush/RichPush/RichPushHttpClient.swift, Tests/Common/Service/UserAgentUtilTest.swift
part of [MBL-540](https://linear.app/customerio/issue/MBL-540/react-native)
- Updated `UserAgentUtil` to provide separate user agents for main target and NSE
- Added a separate NSE `SdkClient` to generate user agent from client using the same code
- Updated `RichPushHttpClient` to use NSE-specific user agent
- Removed unused methods
- Added tests for NSE headers
=> chore: add nse user agent support

Sources/MessagingInApp/Gist/GistDelegate.swift
- An in-app message is sent to an iOS device.
- User opens the keyboard and begins typing.
- Issue arises when the in-app message shows on the screen, as the user is either blocked from closing the message or continuing to type.
This behavior prevents interaction with the app, as displaying of the in-app message disrupts the current activity (e.g., typing or moving back to previous screen) and makes it difficult for the user to manage actions. 
Dismiss keyboard when in-app message shows up on the screen.
The change has been tested on :
- iOS CDP SDK (CDP)
https://github.com/user-attachments/assets/c4095ee4-c09a-42cb-96e0-3d9a5d937366
=> fix: dismiss keyboard on showing in app message on CDP SDK

Sources/MessagingInApp/Gist/Network/Endpoints/QueueEndpoint.swift, Sources/MessagingInApp/Gist/Network/Endpoints/Utilities/Headers.swift, Sources/MessagingInApp/Gist/Network/GistQueueNetwork.swift
closes: https://linear.app/customerio/issue/MBL-495/move-to-v2-apis-of-gist-and-add-sdk-reporting
changes:
- Upgrade user queue endpoint path to v2
- Added SDK version and platform in request headers
=> chore: move to v2 for user queue request and user agent in headers

Apps/fastlane/Fastfile
This PR adds the Firebase Distribution groups for 'feature-branch', 'next', and 'public' in addition to the current 'all-builds' and 'stable-builds' groups.
=> chore: update Fastfile to publish to new distribution groups

Sources/MessagingPush/Config/MessagingPushConfigBuilder.swift, Sources/MessagingPush/Config/MessagingPushConfigOptions.swift, Sources/MessagingPush/RichPush/RichPushDeliveryTracker.swift, Sources/MessagingPush/RichPush/RichPushHttpClient.swift, Tests/MessagingPush/Config/MessagingPushConfigBuilderTest.swift, Tests/MessagingPush/HttpClientTest.swift
closes: [MBL-652: Push Notifications not recording. "Delivered" metrics for iOS despite receiving messages on device](https://linear.app/customerio/issue/MBL-652/push-notifications-not-recording-delivered-metrics-for-ios-despite)
changes:
- add support for region in the push module
- update session API host with region
- added test
=> chore: added region support in NSE

Sources/MessagingInApp/Gist/Managers/MessageManager.swift, Sources/MessagingInApp/Gist/Utilities/String.swift, Tests/MessagingInApp/Gist/Utilities/StringPercentEncodeTests.swift
fixes: [MBL-762](https://linear.app/customerio/issue/MBL-762/[bug]-ios-sdk-strips-fragment-from-urls-in-legacy-in-app-messages)
- Encoded action URL before extracting it for `loadPage` action to retain fragment URL part
- Added string extension to encode specific characters
- Added relevant tests
```
gist://loadPage?url=https://docs.customer.io/sdk/ios/in-app/set-up-in-app/#set-up-in-app-messaging
```
**Before:**
```
https://docs.customer.io/sdk/ios/in-app/set-up-in-app/
```  
**After:**
```
https://docs.customer.io/sdk/ios/in-app/set-up-in-app/#set-up-in-app-messaging
```
=> chore: encode loadPage action URL

Sources/Common/Type/ScreenView.swift, Sources/DataPipeline/Config/DataPipelineConfigOptions.swift, Sources/DataPipeline/Config/SDKConfigBuilder.swift, Sources/DataPipeline/DataPipelineImplementation.swift, Sources/DataPipeline/Plugins/ScreenFilterPlugin.swift, Sources/DataPipeline/Type/Aliases.swift, Tests/Common/Type/ScreenViewTest.swift, Tests/DataPipeline/Plugin/ScreenViewsFilterPluginTest.swift, Tests/DataPipeline/Support/Segment.swift
closes: [MBL-756: Add config to iOS SDK](https://linear.app/customerio/issue/MBL-756/add-config-to-ios-sdk)
- Added `screenViewUse` enum option to allow disable sending screen view events to server and use them locally only
- Added `ScreenFilterPlugin` to filter events based on the `screenViewUse` configuration
- Added tests to ensure functionality
- `All` -> Sends all screen events to the server (same as before) - Default behavior
- `InApp` -> Retains screen events locally for in-app use only
```swift
let config = SDKConfigBuilder(cdpApiKey: cdpApiKey)
.screenViewUse(screenView: .all)
CustomerIO.initialize(withConfig: config.build())
```
=> feat: add option to disable screen view usage

Apps/APN-UIKit/APN UIKit/Base.lproj/Main.storyboard, Apps/APN-UIKit/APN UIKit/Info.plist
part of: [MBL-742](https://linear.app/customerio/issue/MBL-742/has-easy-to-understand-app-name)
- Renamed app from `APN UIKit` to `Native iOS`
- Updated app name on the Login Screen for consistency
Please refer to linked ticket for more details about these changes.
**Launcher**
**Login Screen**
=> chore: update apn sample app name

Sources/MessagingInApp/Gist/Managers/MessageManager.swift, Sources/MessagingInApp/Gist/Managers/ModalViewManager.swift, Sources/MessagingInApp/Gist/Managers/Models/Message.swift, Sources/MessagingInApp/Gist/Utilities/UIColor+Hex.swift, Tests/MessagingInApp/Utilities/UIColor+HexTest.swift
When sending an in-app message to the mobile apps, the specified `Overlay Color` in the in-app message editor is not reflected on the message shown on the app.
The value `overlayColor` sent to the mobile SDK from the server along with the in-app message payload is ignored and not used to set the in-app message overlay color.
Instead a hard-coded color is used for all message.
https://github.com/user-attachments/assets/ed33529a-cc7c-4aba-ba97-a8f7a20135bb
=> fix: Fix in-app messages overlay color ignored from message payload

.github/workflows/build-sample-apps.yml, Apps/fastlane/Fastfile
part of: [MBL-710](https://linear.app/customerio/issue/MBL-710/single-app-per-platform-distributed-to-firebase)
- Updated `Build Sample Apps` action to push only primary app to relevant channels
- Modified `get_build_test_groups` lane to decouple from GitHub and accept arguments for passing Firebase distribution groups when distributing sample apps
Please refer to linked ticket for detailed expectations regarding channel distribution.
=> chore: build primary sample app

Apps/APN-UIKit/APN UIKit.xcodeproj/project.pbxproj, Apps/APN-UIKit/APN UIKit/Base.lproj/Main.storyboard, Apps/APN-UIKit/APN UIKit/Router/DashboardRouter.swift, Apps/APN-UIKit/APN UIKit/View/DashboardViewController.swift, Apps/APN-UIKit/APN UIKit/View/InlineInAppMessageUikitViewController.swift, Sources/MessagingInApp/Views/GistInlineInAppMessageView.swift, Sources/MessagingInApp/Views/UIKitInline.swift
part of: [MBL-826](https://linear.app/customerio/issue/MBL-826/create-placeholder-ui-for-swiftui-and-uikit), [MBL-827](https://linear.app/customerio/issue/MBL-827/integrate-inline-in-app-message-in-placeholder-screen)
- Updated APN sample app to include UIKit examples for inline in-app messages
- Made `elementId` in `InlineMessageUIView` configurable from Storyboard by marking it as `@IBInspectable`
- Updated `InlineMessageUIView` to automatically dismiss inline messages on `deinit`
=> chore: add uikit inline message sample

Sources/MessagingInApp/Gist/Managers/InlineMessageManager.swift, Sources/MessagingInApp/Gist/Managers/MessageManager.swift, Sources/MessagingInApp/Gist/Managers/ModalMessageManager.swift, Sources/MessagingInApp/Views/GistInlineInAppMessageView.swift
- Simplified `onMessageDisplayed` and `onMessageDismissed` for both modal and inline message managers
- Added handling for `InlineMessageState` in `GistInlineMessageUIView`
=> chore: process next inline message on dismiss

Sources/MessagingInApp/Gist/Views/GistModalViewController.swift
Fixes: [MBL-866](https://linear.app/customerio/issue/MBL-866/[ios]-fix-incorrect-message-height-for-topbottom-positioning)
For some modal in-app messages, when positioned at the top/bottom, the content is not shown fully and is scrollable for top/bottom positions but not for centered content.
https://github.com/user-attachments/assets/04086f32-c08a-4e37-9320-a2070f9cc9b6
The `GistView` that contains the webiew that shows the message was being constraint to the top of the screen, making our height calculation incorrect because it didn't take into account the safe area.
Here are examples after the fix:
https://github.com/user-attachments/assets/855660ab-8c1d-44e4-9cc2-aba439ce83f5 
https://github.com/user-attachments/assets/19ff5edf-d05a-4b0a-af4c-703e0bdd2b7d
=> chore: Fix GistView constaints to avoid incorrectly scrolling content for message positioned top/bottom

.github/actions/build-sample-app/action.yml, .github/workflows/build-sample-apps.yml
- Fixed `commitsAheadCount` in `BuildInfoMetadata`
- Updated workflow to add fallback for cases where tags are not fetched properly
| Before |  After |
|-|-|
| ![img_before](https://github.com/user-attachments/assets/1c9ec2a8-35be-42b1-a94b-ae2b94fe43e9) | ![img_after](https://github.com/user-attachments/assets/643843bd-6c57-4408-8e26-3fe9b434c347) |
=> chore: fix commits ahead count

Apps/APN-UIKit/APN UIKit/Base.lproj/Main.storyboard, Apps/APN-UIKit/APN UIKit/Util/BuildInfoMetadata.swift, Apps/APN-UIKit/APN UIKit/View/BaseViewController.swift, Apps/APN-UIKit/APN UIKit/View/DashboardViewController.swift
Minor polishing to the APN testbed app. The changes mostly in the storyboard and one change in the source code to build the attributedText for the metadata details.
In smaller screens the set of buttons should be scrollable while the top and bottom areas remain fixed
Before the change:
After:
=> chore: APN Testbed UI Polishing

CustomerIODataPipelines.podspec, Package.swift
Complete each step to get your pull request merged in. [Learn more about the workflow this project uses](https://github.com/customerio/customerio-ios/blob/develop/docs/dev-notes/GIT-WORKFLOW.md). 
Testing:
- tested and verified SPM and CocoaPods config: 
- cleaned local libraries, then installed them again, and confirmed the right versions are installed
- tested the building of apps `APN-UIKit` (uses SPM) and `CocoaPods-FCM` (uses CocoaPods)
- verified that `APN-UIKit` app reports multiple `Application Installed` events when uses library version `1.5.14+cio.1`, and that it doesn't do that after the version is updated to `1.7.3+cio.1`
=> fix: Analytics version updated to 1.7.3+cio.1

.github/workflows/deploy-sdk.yml
`codeclimate/velocity-deploy-action` Github action started [failing](https://github.com/customerio/customerio-expo-plugin/actions/runs/14379532878/job/40319773344), which is blocking SDK release, we are temporarily disabling it to enables releasing
=> chore: Remove Code Climate Velocity Deployment

Sources/MessagingInApp/Config/MessagingInAppConfigBuilder.swift, Tests/MessagingInApp/Config/MessagingInAppConfigBuilderTest.swift
part of: [MBL-1052](https://linear.app/customerio/issue/MBL-1052/flutter-sdk-region-is-not-set-correctly-by-default)
- Updated `MessagingInAppConfigBuilder.build([String: Any?])` to parse region leniently and fall back to default region if parsing fails instead of blocking initialization
- Updated tests to validate the behavior
=> fix: simplify region parsing in wrapper in-app initialization

Sources/Common/Util/Log.swift, Sources/Common/Util/SystemLogger.swift, Sources/Common/autogenerated/AutoDependencyInjection.generated.swift, Sources/Common/autogenerated/AutoMockable.generated.swift
Closes: [MBL-1072](https://linear.app/customerio/issue/MBL-1072/implement-unified-logging-interface-on-ios)
This PR aligns the Customer IO iOS SDK `Logger` interface to the [unified interfaces definitions](https://www.notion.so/custio/Mobile-SDK-unified-logging-interfaces-1dc4302f4c2b80d08bacd478ca8bbf7e).
The main change in the interface is that logging functions now include a `tag` that will allow us to easily filter logs in the future by module.
Some notable changes in this PR:
- I made sure that the same `Logger` interface was used to avoid having two versions and go through deprecation process
- I've intentionally made `tag` parameter optional for now so we don't have to change any existing code that uses the existing `Logger` interface, I am using extension functions to ensure …
=> chore: Mbl 1072 update logger interface

Sources/Common/Util/Log.swift, Tests/Common/Util/LoggerTest.swift
Closes: [MBL-1072](https://linear.app/customerio/issue/MBL-1072/implement-unified-logging-interface-on-ios)
This PR adds unit tests for the `Logger` changes done in PR: #887
=> chore: Add tests for unified logger implementation

Apps/APN-UIKit/APN UIKit/AppDelegate.swift, Apps/CocoaPods-FCM/src/App.swift, Apps/CocoaPods-FCM/src/AppDelegate.swift
Changes:
- Sample apps are updated to use new AppDelegates and Deep-Linking
Testing:
- the easiest way to get a device-token is to copy from Xcode console
- Basic PN: 
- Expectation: This will send the default testing PN, which should work in & out of the app
- Triggering:
- APN: Send test PN from https://fly.customer.io/workspaces/122175/settings/actions/push/ios
- FCM: Send test PN from https://fly.customer.io/workspaces/111525/settings/actions/push/ios
- PN with Deep-link: 
- Expectation: This will send the PN payload with URL (google.com), which should work in & out of the app, and tap should open this URL in Safari or Google app
- Triggering:
- APN: Use button `Send test...` in test-campaign PN-config from https://fly.customer.io/workspaces/122175/journeys/composer/actions/365
- FCM: …
=> chore: Swizzling removal - iOS SDK (Sample apps)

Apps/APN-UIKit/APN UIKit/AppDelegate.swift, Apps/APN-UIKit/NotificationServiceExtension/NotificationService.swift, Apps/CocoaPods-FCM/src/AppDelegate.swift, Sources/MessagingPush/Config/MessagingPushConfigBuilder.swift, Sources/MessagingPush/Integration/CioProviderAgnosticAppDelegate.swift, Tests/MessagingPush/Integration/CioProviderAgnosticAppDelegateTests.swift, Tests/MessagingPushFCM/Integration/FirebaseMessagingMocks.swift, Tests/Shared/Mocks/UIKitDelegateMocks.swift
There was incompatibility between the old default behaviour for `showPushAppInForeground` and the new no-swizzling approach:
- The old system had `showPushAppInForeground` set to `true` as default, so if this property is not set, notifications will be shown in the foreground.
- The new system was originally implemented to be compatible with iOS' default behavior, which meant not implementing `UNUserNotificationCenterDelegate` would NOT show notifications in the foreground.
This PR changes the behavior of the new system to be backward compatible, so not implementing the `UNUserNotificationCenterDelegate` in the customer's AppDelegate will show notifications based on `showPushAppInForeground`.
If customers want fine-grained control, they should implement `UNUserNotificationCenterDelegate`. …
=> feat: Swizzling removal - Compatibility improvements for `showPushAppInForeground`

Sources/DataPipeline/DataPipelineImplementation.swift, Sources/DataPipeline/Util/DataPipelinesLogger.swift, Sources/DataPipeline/autogenerated/AutoMockable.generated.swift, Tests/DataPipeline/DataPipelineInteractionTests.swift, Tests/DataPipeline/Util/DataPipelinesLoggerTests.swift
Part of: [MBL-1074](https://linear.app/customerio/issue/MBL-1074/update-push-notification-logging-for-ios)
Closes: [MBL-1112](https://linear.app/customerio/issue/MBL-1112/update-identify-logs)
This PR implements log definitions as defined in the log definitions repo https://github.com/customerio/mobile-log-definitions/pull/8
- Adds logs for token profile registration
- Added unit test for the wrapper logger and call sites
- Logs after implementation are as follows
```
[Init] Creating new instance of CustomerIO SDK version: 3.8.2...
[Init] Initializing SDK module DataPipeline...
[Init] CustomerIO DataPipeline module is initialized and ready to use
[Init] CustomerIO SDK is initialized and ready to use
[Init] Initializing SDK module MessagingPush...
[Init] CustomerIO MessagingPush module is …
```
=> chore: Update push token identify logs

CustomerIOMessagingPushFCM.podspec, Package.swift, dangerfile.js
This PR updates the Firebase SDK version constraints to ensure consistency between Swift Package Manager (SPM) and CocoaPods integrations. Both now explicitly support versions from 8.7.0 up to (but not including) 12.0.0.
Changes
•	SPM (Package.swift):
Updated .package declaration to use a closed range:
```
.package(name: "Firebase", url: "https://github.com/firebase/firebase-ios-sdk.git", "8.7.0"..<"12.0.0")
```
•	CocoaPods (.podspec):
Updated dependency constraint to:
```
spec.dependency "FirebaseMessaging", ">= 8.7.0", "< 12.0.0"
```
Testing:
- In order to ensure its working, you add latest FCM dependency version in sample apps and they should not conflict with CIO FCM dependency.
=> fix: FCM version upper and lower bound  

Sources/DataPipeline/CustomerIO+Events.swift, Sources/DataPipeline/DataPipeline.swift, Sources/DataPipeline/Util/DictionarySanitizer.swift, Tests/DataPipeline/Util/DictionarySanitizerTests.swift
Fixes: [MBL-1196](https://linear.app/customerio/issue/MBL-1196/floating-point-nan-or-infinity-values-should-be-managed-on-android)
- We allow customers to attach arbitrary `Map` of properties with events and screen tracking. The input is defined as `Map<String, Any>`. That means that customers can pass any value as value in a map entry
- These values need to be serialized into a JSON format to be transmitted to our servers
- Customers can pass values that are not supported by JSON. For example, a `Double` value of `Double.NaN` or the result of dividing 0/0 or smth similar. These values are not supported by JSON
This causes the serialization process to fail by crashing on Android and it defaults to an incorrect value of `0` on iOS
- We are creating a sanitization step for those types of …
=> fix: Sanitize unsupported numeric values

.github/workflows/test.yml, Apps/APN-UIKit/APN UIKit.xcodeproj/project.pbxproj, Apps/CocoaPods-FCM/Podfile, Apps/Common/Package.swift, CustomerIOMessagingPushFCM.podspec, Package.swift, scripts/update-ios-deployment-target-for-ci.sh
- Updated `CustomerIOMessagingPushFCM.podspec` to allow Firebase version up to `<13`
- Updated `Package.swift` to allow Firebase version up to `<13`
- FCM sample app compiled successfully without dependency conflicts
- Device token generation worked as expected
- Push notifications were delivered, and metrics were tracked correctly
- Push including universal links and images worked as expected
⚠️ [Firebase 12 requires a minimum iOS deployment target of 15](https://firebase.google.com/support/release-notes/ios#version_1200_-_july_15_2025)
- #929 
- [Slack thread](https://customerio.slack.com/archives/C06H7MMLH6C/p1753110172433819?thread_ts=1753108436.450109&cid=C06H7MMLH6C)
=> feat: allow Firebase 12 support

Sources/Common/CustomerIOInstance.swift, Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/DataPipeline/DataPipeline.swift, Sources/DataPipeline/DataPipelineImplementation.swift, Tests/Common/APITest.swift, Tests/DataPipeline/APITest.swift, Tests/DataPipeline/DataPipelineCompatibilityTests.swift, Tests/DataPipeline/DataPipelineInteractionTests.swift, Tests/MessagingPush/MessagingPushIntegrationTests.swift, api-docs/CioDataPipelines.api, api-docs/internal/CioInternalCommon.api
Closes: [MBL-1299](https://linear.app/customerio/issue/MBL-1299/device-and-user-enrichment-api-alignment)
Tweaks public API `deviceAttributes` to be `setDeviceAttributes` for clarify and consistency with other SDKs
=> chore: Turn deviceAttributes into setDeviceAttributes

Apps/APN-UIKit/APN UIKit/View/Customisation/CustomDataViewController.swift, Apps/CocoaPods-FCM/src/View/CustomAttributeView.swift, Sources/Common/CustomerIOInstance.swift, Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/DataPipeline/DataPipeline.swift, Sources/DataPipeline/DataPipelineImplementation.swift, Tests/Common/APITest.swift, Tests/DataPipeline/APITest.swift, api-docs/CioDataPipelines.api, api-docs/internal/CioInternalCommon.api
Closes: [MBL-1299](https://linear.app/customerio/issue/MBL-1299/device-and-user-enrichment-api-alignment)
Tweaks public API `profileAttributes` to be `setProfileAttributes` for clarify and consistency with other SDKs
=> chore: Turn profileAttributes into setProfileAttributes

Sources/Common/CustomerIOInstance.swift, Sources/DataPipeline/CustomerIO+Events.swift, Sources/DataPipeline/DataPipelineImplementation.swift
Closes: [MBL-1298](https://linear.app/customerio/issue/MBL-1298/tracking-api-alignment)
Simplified the CustomerIO tracking API by removing all `Codable` parameter overloads for identify, track, and screen methods, keeping only the `[String: Any]` map-based versions.
- Removed Codable overloads from:
- CustomerIOInstance protocol and CustomerIO class implementation
- CustomerIO+Events.swift extension methods
- Removed parameter-less overloads:
- track(name:) without properties
- screen(title:category:) without properties
- identify<T: Codable>(traits:) without userId
- Simplified API: Single consistent method signature per function
- Better maintainability: Reduced code complexity and potential confusion
=> chore: Deprecating unnecessary tracking APIs

Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/MessagingPush/Integration/CioProviderAgnosticAppDelegate.swift, Tests/MessagingPush/Integration/CioProviderAgnosticAppDelegateTests.swift, Tests/Shared/Mocks/UIKitDelegateMocks.swift
part of: [MBL-1277](https://linear.app/customerio/issue/MBL-1277/react-native-sdk-443-conflict-with-facebook-login-sdk)
When using `CioAppDelegateWrapper` in FCM setup, the `application(_:open:options:)` method was not being triggered which broke custom scheme deep links and possibly other URL based flows (e.g., OAuth callbacks). This issue was caused by the selector not being declared in `implementedOptionalMethods`, preventing proper method forwarding from `UIApplication`.
- Added the missing selector `application(_:open:options:)` to `implementedOptionalMethods` array in `CioProviderAgnosticAppDelegate`
- Implemented `application(_:open:options:)` in `CioProviderAgnosticAppDelegate` to forward custom scheme handling to customer app
- Ensured the method works with both APN and FCM …
=> chore: add missing custom scheme url handling to app delegate wrapper

Sources/Common/autogenerated/AutoMockable.generated.swift, Sources/MessagingPush/Integration/CioProviderAgnosticAppDelegate.swift, Sources/MessagingPush/MessagingPushInstance.swift, Sources/MessagingPush/PushHandling/ManualPushHandling+UserNotifications.swift, Sources/MessagingPush/autogenerated/AutoMockable.generated.swift, Sources/MessagingPushAPN/MessagingPushAPN.swift, Sources/MessagingPushFCM/MessagingPushFCM.swift, Tests/MessagingPush/Integration/CioProviderAgnosticAppDelegateTests.swift, Tests/MessagingPushAPN/Integration/CioAppDelegateAPNTests.swift, Tests/MessagingPushFCM/Integration/CioAppDelegateFCMTests.swift, api-docs/internal/CioMessagingPush.api
closes: https://linear.app/customerio/issue/MBL-1343/ios-26-xcode-26-beta-build-fails-messagingpush-does-not-conform-to
Problem:
Xcode 16 Beta has stricter protocol conformance validation that detected availability annotation mismatches between protocol definitions and implementations with @available(iOSApplicationExtension, unavailable) annotations.
Solution: Remove Protocol Methods and Update Callers
Note: SPM is resolving it by itself but its an issue on the cocoapods version.
=> fix: build issues on xcode 26 beta
