- README.md
Adds docs for push event tracking & [auto tracking](https://github.com/customerio/customerio-ios/pull/63)
> docs: push event tracking

- README.md
> Not ready to merge until FCM setup docs are added.
> docs: send rich push using FCM

- Sources/Tracking/Util/Log.swift
Making a beta deploy off of commit `535d0be1bdbd3a43d9ba1fe2fabeb4002ea5d35f` on the `alpha` branch. 
I will perform a rebase to merge all commits into `beta` to match `alpha` and `beta` together.
> Beta 1.0.0 deploy

- Sources/Tracking/CustomerIOImplementation+ScreenViews.swift
- Sources/Tracking/Service/Request/TrackRequestBody.swift
- Tests/Tracking/Service/Request/TrackRequestBody.swift
> fix: track events type in HTTP requests

- Sources/Tracking/CustomerIO.swift
- Sources/Tracking/CustomerIOImplementation.swift
- Sources/Tracking/Service/Request/TrackRequestBody.swift
- Sources/Tracking/autogenerated/AutoMockable.generated.swift
Closes: https://github.com/customerio/customerio-ios/issues/112
> fix: remove custom jsonencoder public functions

- Sources/Tracking/CustomerIOImplementation.swift
- Sources/Tracking/Service/Request/TrackRequestBody.swift
- Tests/Tracking/CustomerIOImplementationTest.swift
Fixes: https://github.com/customerio/customerio-ios/issues/134
> fix: data:null as HTTP request body

- .github/workflows/deploy-cocoapods.yml
- .github/workflows/deploy-git-tag.yml
> ci: notify team of releases of SDK

- Sources/Tracking/Service/HttpClient.swift
- Tests/Tracking/Service/HttpClientTest.swift
Closes: https://github.com/customerio/issues/issues/6983
> refactor: use bundle id instead of app name user-agent

- Sources/Tracking/Util/DeviceInfo.swift
- Tests/Tracking/Util/DeviceInfoTest.swift
Closes: https://github.com/customerio/issues/issues/7046
> fix: use dashes instead of underscores device locale

- .github/workflows/test.yml
- .gitignore
- fastlane/Scanfile
- scripts/generate-code-coverage-report.sh
> ci: setup code coverage reporting

- Sources/MessagingPush/util/DeviceAttributesProvider.swift
- Sources/Tracking/Util/DeviceInfo.swift
- Sources/Tracking/autogenerated/AutoMockable.generated.swift
- Tests/MessagingPush/util/DeviceAttributesProviderTest.swift
Closes https://github.com/customerio/issues/issues/7128
> feat: add device_manufacturer device attribute

- docs/dev-notes/BACKGROUND-QUEUE.md
Explain a concept of the background queue that previously was not explained. 
> docs: update background queue doc to explain snapshots

- .github/workflows/test.yml
- README.md
> ci: improve success of code coverage uploading

- .github/workflows/deploy-cocoapods.yml
- CustomerIO.podspec
- CustomerIOMessagingInApp.podspec
> ci: push inapp to cocoapods

- .github/workflows/deploy-cocoapods.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
> ci: install swift 5.5 and 5.6 in CI testing

- Sources/Common/Service/HttpClient.swift
- Sources/Common/Store/SdkConfig.swift
- Sources/Common/Type/SDKWrapperConfig.swift
- Sources/Common/Version.swift
- Sources/Tracking/CustomerIO.swift
- Tests/.swiftlint.yml
- Tests/Common/Service/HttpClientTest.swift
- Tests/Shared/HttpTest.swift
- scripts/update_version.sh
Allows our react native SDK to modify the user-agent in HTTP requests. 
> feat: sdk wrappers modify user-agent

- scripts/generate-code-coverage-report.sh
> ci: fix generating code coverage

- CustomerIOMessagingInApp.podspec
- Package.resolved
- Package.swift
> fix: updating gist dependency version

- Sources/Tracking/CustomerIO.swift
> fix: restricting create own instance

- dangerfile.js
> ci: dont forget to update SPM or cocoapods

- CustomerIOMessagingInApp.podspec
> fix: updated gist version in podspec

- Sources/Common/Extensions/UIApplicationExtensions.swift
- Sources/Tracking/CustomerIOImplementation+ScreenViews.swift
Duplicate of https://github.com/customerio/customerio-ios/pull/214, but merging into the correct branch. 
> fix: fix compile time errors notification service extensions

- CHANGELOG.md
- CustomerIO.podspec
- CustomerIOCommon.podspec
- CustomerIOMessagingInApp.podspec
- CustomerIOMessagingPush.podspec
- CustomerIOMessagingPushAPN.podspec
- CustomerIOMessagingPushFCM.podspec
- CustomerIOTracking.podspec
- Sources/Common/Extensions/UIApplicationExtensions.swift
- Sources/Common/Version.swift
- Sources/MessagingPush/util/DeviceAttributesProvider.swift
- Sources/Tracking/CustomerIOImplementation+ScreenViews.swift
- Tests/MessagingPush/util/DeviceAttributesProviderTest.swift
Automatically syncing these 2 branches failed by the CI server. Merge this pull request manually instead.
> Merge main into develop

- .github/workflows/test.yml
> ci: test cocoapods in tests

- .github/workflows/deploy-git-tag.yml
- Tests/MessagingPush/MessagingPushIntegrationTest.swift
- Tests/Shared/SampleData/CustomAttributesSampleData.swift
- Tests/Tracking/CustomerIOIntegrationTests.swift
- tests: add tests missing from v1 snake_case bug fix
- ci: make ci deploy on v1 branch
> refactor: add tests, make v1 trigger deploy on CI

- .github/workflows/deploy-cocoapods.yml
- .github/workflows/deploy-git-tag.yml
- .github/workflows/promote.yml
Changes the Slack channel for deployment messages to the new mobile-deployments channel Refs customerio/issues#9014
> ci: changes Slack deployment message channel

- Sources/Common/Background Queue/QueueRunRequest.swift
- Tests/Shared/IntegrationTest.swift
- Tests/Shared/Stub/HttpRequestRunnerStub.swift
- Tests/Shared/UnitTest.swift
- Tests/Shared/XCTestCaseExtensions.swift
- Tests/Tracking/CustomerIOIntegrationTests.swift
This reverts commit ef0c4285bbe1a908e9695258f84cde26b62eeb80.
> fix: revert 2.0.2 as it was found unstable

- Sources/MessagingInApp/MessagingInAppImplementation.swift
- Tests/MessagingInApp/MessagingInAppImplementationTest.swift
> fix: gist set user token incase identifier exists

- Sources/MessagingInApp/MessagingInAppImplementation.swift
- Tests/MessagingInApp/MessagingInAppImplementationTest.swift
Context: https://customerio.slack.com/archives/C036FTE6UJ0/p1675374046990879
> fix: in-app missing event

- .github/workflows/build-sample-apps.yml
- Apps/.gitignore
- Apps/CocoaPods-FCM/src/GoogleService-Info.plist
- Apps/CocoaPods-FCM/test cocoapods.xcodeproj/project.pbxproj
- Apps/fastlane/Fastfile
- Gemfile
- Gemfile.lock
- Sources/Common/Service/HttpClient.swift
- docs/dev-notes/DEVELOPMENT.md
> ci: fix code signing setup on CI server

- .github/workflows/pr-helper.yml
> ci: remove unnecessary warning

- CustomerIOMessagingInApp.podspec
3.0.0 up to (but not including) 4.0.0
> fix: auto update gist in CocoaPods

- .github/workflows/deploy-sdk.yml
> ci: fix sd not in path

- CustomerIOMessagingInApp.podspec
- Package.swift
> fix: in-app universal link redirection support

- Apps/APN-UIKit/APN UIKit/AppDelegate.swift
This PR has feature implementation of in-app Dismiss Message. Import `CioMessagingInApp` and call the method `MessagingInApp.shared.dismissMessage()` to dismiss active in-app message shown on the screen.
> refactor: in-app dismissMessage feature implementation

- Apps/APN-UIKit/APN UIKit/Base.lproj/Main.storyboard
- Apps/APN-UIKit/APN UIKit/View/BaseViewController.swift
- Apps/APN-UIKit/APN UIKit/View/Customisation/CustomDataViewController.swift
- Apps/APN-UIKit/APN UIKit/View/DashboardViewController.swift
- Apps/APN-UIKit/APN UIKit/View/Extension/ViewExtension.swift
- Apps/APN-UIKit/APN UIKit/View/LoginViewController.swift
- Apps/APN-UIKit/APN UIKit/View/SettingsViewController.swift
This PR adds accessibility identifiers to support Appium test cases.
> refactor: appium accessibility identifiers APN/UIKit sample

- Apps/APN-UIKit/APN UIKit/Util/DeepLinksHandlerUtil.swift
> chore: fix universal link handling in sample ui-kit app

- Sources/Common/Extensions/StringExtensions.swift
- Sources/Tracking/CustomerIOImplementation.swift
- Tests/Common/Extensions/StringExtensionsTest.swift
- Tests/Tracking/CustomerIOImplementationTest.swift
Fixes issue for https://secure.helpscout.net/conversation/2267893231/217421/
closes https://github.com/customerio/opsbugs/issues/3603
> fix: prevent api calls when identifier is empty

- Apps/APN-UIKit/APN UIKit.xcodeproj/project.pbxproj
- Apps/APN-UIKit/APN UIKit/Base.lproj/Main.storyboard
- Apps/APN-UIKit/APN UIKit/Util/DeepLinksHandlerUtil.swift
- Apps/APN-UIKit/APN UIKit/Util/MetadataUtil.swift
- Apps/APN-UIKit/APN UIKit/View/BaseViewController.swift
- Apps/APN-UIKit/APN UIKit/View/Customisation/CustomDataViewController.swift
- Apps/APN-UIKit/APN UIKit/View/DashboardViewController.swift
- Apps/APN-UIKit/APN UIKit/View/SettingsViewController.swift
Fixed the issues reported during testing of the sample app.
> refactor: uikit apn sample app test fixes 

- scripts/cocoapods_override_sdk.rb
> refactor: non-prod install cocoapods script named params

- Apps/APN-UIKit/APN UIKit.xcodeproj/project.pbxproj
- Apps/APN-UIKit/APN UIKit/View/DashboardViewController.swift
- Apps/APN-UIKit/APN UIKit/View/Extension/DateExtension.swift
> refactor: minor improvement to uikit sample app

- Sources/Common/Extensions/StringExtensions.swift
- Sources/Common/Service/CIOApiEndpoint.swift
- Sources/Common/autogenerated/AutoDependencyInjection.generated.swift
- Sources/Common/autogenerated/AutoLenses.generated.swift
- Sources/Common/autogenerated/AutoMockable.generated.swift
- Sources/MessagingInApp/autogenerated/AutoDependencyInjection.generated.swift
- Sources/MessagingInApp/autogenerated/AutoLenses.generated.swift
- Sources/MessagingInApp/autogenerated/AutoMockable.generated.swift
- Sources/MessagingPush/autogenerated/AutoDependencyInjection.generated.swift
- Sources/MessagingPush/autogenerated/AutoLenses.generated.swift
- Sources/MessagingPush/autogenerated/AutoMockable.generated.swift
- Sources/MessagingPushAPN/autogenerated/AutoDependencyInjection.generated.swift
- Sources/MessagingPushAPN/autogenerated/AutoLenses.generated.swift
- Sources/MessagingPushAPN/autogenerated/AutoMockable.generated.swift
- Sources/MessagingPushFCM/autogenerated/AutoDependencyInjection.generated.swift
- Sources/MessagingPushFCM/autogenerated/AutoLenses.generated.swift
- Sources/MessagingPushFCM/autogenerated/AutoMockable.generated.swift
- Sources/Tracking/autogenerated/AutoDependencyInjection.generated.swift
- Sources/Tracking/autogenerated/AutoLenses.generated.swift
- Sources/Tracking/autogenerated/AutoMockable.generated.swift
- Tests/Common/Service/HttpEndpointTest.swift
> chore: autogenerated sourcery files

- Sources/MessagingInApp/Gist/Gist.swift
- Sources/MessagingInApp/Gist/Managers/MessageManager.swift
- Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift
- Sources/MessagingInApp/Gist/Managers/Models/Message.swift
More details on it can be found on [Slack](https://customerio.slack.com/archives/C036FTE6UJ0/p1697540277891429).
> fix: in-app positioning and persistence

- Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift
- Sources/MessagingInApp/Gist/Managers/Models/Message.swift
- Sources/MessagingInApp/Gist/Network/Models/UserQueueResponse.swift
Fixes issue: https://github.com/customerio/issues/issues/11663
> fix: add priority field to message and sorting by priority within local store

- Sources/Common/Communication/EventStorage.swift
- Sources/Common/autogenerated/AutoDependencyInjection.generated.swift
- Sources/DataPipeline/DataPipelineImplementation.swift
- Sources/DataPipeline/plugins/DataPipelinePublishedEvents.swift
- Sources/MessagingInApp/MessagingInAppImplementation.swift
- Sources/MessagingPush/MessagingPushImplementation.swift
- Sources/Templates/AutoDependencyInjection.stencil
Broken down and reworked PR for the Event Bus implementation.
More Details about the previous implementation and flow can be found in the previous [PR](https://github.com/customerio/customerio-ios/pull/440)
PR 5: Holds the usage of the event bus handler and its working.
> chore: event bus usage pr5

- Tests/Tracking/Util/DeviceAttributesProviderTest.swift
> test: fix device attribute provider test cases

- .github/workflows/deploy-sdk.yml
Adding an action `on successful deployment` to relay that to our CodeClimate setup
> Codeclimate deployment action

- Tests/Common/Communication/EventBusTest.swift
Broken down PR for https://github.com/customerio/customerio-ios/pull/454/files#top
Please go through the details in the parent ticket for further context.
> test: added for event bus class

- Sources/DataPipeline/DataPipelineImplementation.swift
more details can be found here:
https://customerio.slack.com/archives/C05UY5J4VLK/p1704830320326159?thread_ts=1704811102.597619&cid=C05UY5J4VLK
> fix: removed last_used from properties 

- Tests/DataPipeline/DataPipelineCompatibilityTests.swift
- Tests/Shared/Stub/DeviceInfoStub.swift
helps: https://linear.app/customerio/issue/MOB-12/improve-cdp-test-coverage
- Added json compatibility tests
> test: data pipeline json compatibility

- Sources/Common/Background Queue/Queue.swift
- Sources/Common/Communication/EventBus.swift
- Sources/Common/Communication/EventBusHandler.swift
- Sources/Common/Communication/EventMemoryStorage.swift
- Sources/Common/Communication/EventStorage.swift
- Sources/Common/CustomerIOInstance.swift
- Sources/Common/autogenerated/AutoMockable.generated.swift
- Sources/DataPipeline/DataPipelineConfigOptions.swift
- Sources/MessagingPush/MessagingPushConfigOptions.swift
- Tests/DataPipeline/DataPipelineInteractionTests.swift
- Tests/Tracking/migration/DataPipelineMigrationAssistantTests.swift
fixes all the linting issues except from `fixme` and `todo`
> chore: fix linting 

- Apps/APN-UIKit/APN UIKit/View/Customisation/CustomDataViewController.swift
- Apps/APN-UIKit/APN UIKit/View/DashboardViewController.swift
- Apps/APN-UIKit/APN UIKit/View/LoginViewController.swift
linked to: https://linear.app/customerio/issue/MBL-71/sample-app-cleanup-with-cdp-sdk-apn-uikit
Includes:
- Using CDP methods in sample app
> chore: consume datapipeline methods in uikit sample app

- Apps/APN-UIKit/APN UIKit/Base.lproj/Main.storyboard
- Apps/APN-UIKit/APN UIKit/Router/DashboardRouter.swift
- Apps/APN-UIKit/APN UIKit/Router/LoginRouter.swift
- Apps/APN-UIKit/APN UIKit/View/SettingsViewController.swift
linked to : https://linear.app/customerio/issue/MBL-71/sample-app-cleanup-with-cdp-sdk-apn-uikit
Includes:
- Updates to router classes
- ui updates in storyboard
> chore: ui and router updates in sample app using cdp sdk

- Sources/MessagingPush/PushHandling/PushEventHandlerProxy.swift
- Sources/MessagingPush/PushHandling/iOSPushEventListener.swift
- Sources/MessagingPush/Store/PushHistory.swift
- Sources/MessagingPush/autogenerated/AutoDependencyInjection.generated.swift
- Tests/.swiftlint.yml
- Tests/MessagingPush/PushHandling/AutomaticPushClickedIntegrationTest.swift
- Tests/MessagingPush/PushHandling/AutomaticPushDeliveredAppInForegroundTest.swift
- Tests/MessagingPush/PushHandling/ManualPushHandlingTest.swift
- Tests/Shared/XCTestCaseExtensions.swift
Fixing all lint errors for automatic push click handling feature changes.
See comments made in the PR for this commit to understand some of the decisions made.
> refactor: fix all lint errors

- .github/workflows/build-sample-apps.yml
- Apps/APN-UIKit/BuildEnvironment.sample.swift
Final PR
closes https://linear.app/customerio/issue/MBL-71/sample-app-cleanup-with-cdp-sdk-apn-uikit
> chore: ci config changes for sample app using cdp write key

- Sources/Common/Background Queue/Queue.swift
- Sources/Common/Background Queue/QueueStorage.swift
- Sources/Common/CustomerIOInstance.swift
- Sources/Common/Util/FileStorage.swift
- Sources/Common/Util/JsonAdapter.swift
- Sources/Common/Util/Log.swift
- Sources/Common/Util/Timer.swift
- Sources/Common/autogenerated/AutoDependencyInjection.generated.swift
- Sources/Common/autogenerated/AutoMockable.generated.swift
- Sources/DataPipeline/CustomerIO.swift
- Sources/MessagingInApp/MessagingInAppImplementation.swift
- Sources/MessagingInApp/Provider/InAppProvider.swift
- Sources/MessagingInApp/autogenerated/AutoMockable.generated.swift
- Sources/MessagingPush/Util/DeepLinkUtil.swift
- Sources/MessagingPush/autogenerated/AutoDependencyInjection.generated.swift
- Sources/Tracking/autogenerated/AutoDependencyInjection.generated.swift
- Sources/Tracking/migration/DataPipelineMigrationAssistant.swift
- Tests/Common/Util/FileStorageTest.swift
- Tests/Common/Util/SimpleTimerTest.swift
- Tests/MessagingPush/Util/DeepLinkUtilTest.swift
- Tests/Shared/Core/UnitTestBase.swift
helps: https://linear.app/customerio/issue/MBL-105/logging-in-modules
Share logger and config among all modules and dependencies including Segment and Gist
> chore: update loglevel in all modules

- Tests/Common/Service/UserAgentUtilTest.swift
Fixes failing test on main-cdp branch that was introduced in recent PR merge.
> test: fix broken test on main-cdp branch

- Sources/Common/Background Queue/QueueStorage.swift
- Sources/Common/Service/HttpRequestRunner.swift
- Sources/Common/Store/QueueInventoryMemoryStore.swift
- Sources/Common/Util/DateUtil.swift
- Sources/Common/Util/DeviceInfo.swift
- Sources/Common/Util/DeviceMetricsGrabber.swift
- Sources/Common/Util/FileStorage.swift
- Sources/Common/Util/JsonAdapter.swift
- Sources/Common/Util/KeyValueStorage.swift
- Sources/Common/Util/LockManager.swift
- Sources/Common/Util/Log.swift
- Sources/Common/Util/SingleScheduleTimer.swift
- Sources/Common/Util/ThreadUtil.swift
- Sources/Common/Util/Timer.swift
- Sources/Common/Util/UIKitWrapper.swift
- Sources/DataPipeline/Util/DeviceAttributesProvider.swift
- Sources/MessagingInApp/Provider/InAppProvider.swift
- Tests/DataPipeline/Core/IntegrationTest.swift
- Tests/DataPipeline/Core/UnitTest.swift
- Tests/MessagingPush/Core/IntegrationTest.swift
- Tests/MessagingPush/HttpTest.swift
- Tests/MessagingPush/PushHandling/AutomaticPushClickedIntegrationTest.swift
- Tests/MessagingPush/PushHandling/AutomaticPushDeliveredAppInForegroundTest.swift
- Tests/MessagingPush/PushHandling/PushEventHandlerTest.swift
- Tests/Migration/DataPipelineMigrationAssistantTests.swift
- Tests/Shared/Core/UnitTestBase.swift
- Tests/Shared/DIGraphTest.swift
helps: [MBL-46](https://linear.app/customerio/issue/MBL-46/remove-digraph)
- Removed `sourcery: InjectRegister` from code
- Fixed tests and files using `DIGraph`
> chore: remove di graph usages

- Sources/Migration/DataPipelineMigrationAssistant.swift
refactor migration class to pass the linting checks. 
part 2 of [linting fixes. ](https://linear.app/customerio/issue/MBL-151/linting-fixes)
> chore: refactored migration class for linting

- Sources/Common/CustomerIOInstance.swift
- Sources/Common/Util/KeyValueStorage.swift
- Sources/Common/autogenerated/AutoDependencyInjection.generated.swift
- Sources/Migration/DataPipelineMigrationAssistant.swift
- Tests/Common/Communication/EventBusHandlerTests.swift
- Tests/Common/Util/KeyValueStorageTest.swift
- Tests/DataPipeline/APITest.swift
- Tests/DataPipeline/Config/SDKConfigBuilderTest.swift
- Tests/DataPipeline/DataPipelineCompatibilityTests.swift
- Tests/DataPipeline/DataPipelineImplementation+ScreenViewsTest.swift
- Tests/DataPipeline/Support/XCTestCaseExtensions.swift
- Tests/MessagingInApp/MessagingInAppImplementationTest.swift
part 1 of the [linting fixes](https://linear.app/customerio/issue/MBL-151/linting-fixes)
> chore: linting fixes

- Sources/Common/Service/Request/MetricRequest.swift
style: Formatting
For some reason not all our source code files are formatted consistently. I ran the `make format` command and there are many files changed due to formatting.
This PR doesn't introduce any changes other than the result of running `make format`
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/customerio/customerio-ios/pull/576).
* #586
* #585
* #581
* #580
* #579
* #578
* #577
* __->__ #576
> style: Formatting

- Apps/VisionOS/VisionOS.xcodeproj/project.pbxproj
- Apps/VisionOS/VisionOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Apps/VisionOS/VisionOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Apps/VisionOS/VisionOS/Assets.xcassets/AccentColor.colorset/Contents.json
- Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Back.solidimagestacklayer/Content.imageset/Contents.json
- Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Back.solidimagestacklayer/Contents.json
- Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Contents.json
- Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Front.solidimagestacklayer/Content.imageset/Contents.json
- Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Front.solidimagestacklayer/Contents.json
- Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Middle.solidimagestacklayer/Content.imageset/Contents.json
- Apps/VisionOS/VisionOS/Assets.xcassets/AppIcon.solidimagestack/Middle.solidimagestacklayer/Contents.json
- Apps/VisionOS/VisionOS/Assets.xcassets/Contents.json
- Apps/VisionOS/VisionOS/Info.plist
- Apps/VisionOS/VisionOS/MainScreen.swift
- Apps/VisionOS/VisionOS/Preview Content/Preview Assets.xcassets/Contents.json
- Apps/VisionOS/VisionOS/VisionOSApp.swift
- CHANGELOG.md
- CustomerIO.podspec
- CustomerIOCommon.podspec
- CustomerIODataPipelines.podspec
- CustomerIOMessagingInApp.podspec
- CustomerIOMessagingPush.podspec
- CustomerIOMessagingPushAPN.podspec
- CustomerIOMessagingPushFCM.podspec
- CustomerIOTracking.podspec
- Sources/Common/Version.swift
- Sources/MessagingInApp/MessagingInAppImplementation.swift
- Sources/MessagingPushAPN/MessagingPushAPN+PushConfigs.swift
Took the latest changes from `main` and resolved the conflicts and merged them in `cdp-main`. 
Conflicts were in `podspec`, `MessagingInAppImplementation`
> chore: merge main into cdp-main

- Apps/APN-UIKit/APN UIKit/AppDelegate.swift
> chore: remove internal modules from sample app

- Apps/VisionOS/VisionOS.xcodeproj/project.pbxproj
- Apps/VisionOS/VisionOS/APIViews/IdentifyView.swift
- Apps/VisionOS/VisionOS/MainScreen.swift
- Apps/VisionOS/VisionOS/ViewUtils/CodeSnippetHelper.swift
This is a PR in a series of PRs to build sample app that runs Identify and Track in VisionPro The app is built to be an interactive walk through guidance for developers who are integrating Customer.io Swift SDK in their VisioPro apps. For more context:
This PR introduces a the "Identify" example screen. It demonstrates the requirements of the API, allows the user to enter profile attributes to be send alongside the identify call.
Ensure identify works as expected end to end
https://github.com/customerio/customerio-ios/assets/142905621/b2e0c805-2a2a-4a2a-9503-992d4baf3704 …
> docs: [vision-os-sample-app][8/n] Identify view

- Apps/VisionOS/VisionOS.xcodeproj/project.pbxproj
- Apps/VisionOS/VisionOS/APIViews/TrackEventsView.swift
- Apps/VisionOS/VisionOS/MainScreen.swift
- Apps/VisionOS/VisionOS/Storage/Payloads.swift
This is a PR in a series of PRs to build sample app that runs Identify and Track in VisionPro The app is built to be an interactive walk through guidance for developers who are integrating Customer.io Swift SDK in their VisioPro apps. For more context:
This PR introduces a the "track event" example screen. It shows the simple code snippet and UI to send and event with properties
Ensure the track event works as expected end to end
https://github.com/customerio/customerio-ios/assets/142905621/93d3fca7-e4da-49dd-9524-0b9f856667e6
--
- #668 
- #667 👈
- #666 
- #665 
- #664 …
> docs: [vision-os-sample-app][9/n] Track events view

- Apps/VisionOS/VisionOS.xcodeproj/project.pbxproj
- Apps/VisionOS/VisionOS/APIViews/ProfileAttributesView.swift
- Apps/VisionOS/VisionOS/CommonViews/PropertiesInputView.swift
- Apps/VisionOS/VisionOS/MainScreen.swift
- Apps/VisionOS/VisionOS/Storage/Payloads.swift
This is a PR in a series of PRs to build sample app that runs Identify and Track in VisionPro The app is built to be an interactive walk through guidance for developers who are integrating Customer.io Swift SDK in their VisioPro apps. For more context:
This PR introduces a screen to demonstrate the usage of the `profileAttributes` dictionary.
https://github.com/customerio/customerio-ios/assets/142905621/ab2b209c-94a1-46d2-825d-53fe50032c75
Ensures profile attributes works end to end
--
- #668  👈 
- #667
- #666 
- #665 
- #664   
- #663
> docs: [vision-os-sample-app][10/n] Profile Attributes

- Apps/VisionOS/VisionOS.xcodeproj/xcshareddata/xcschemes/VisionOS.xcscheme
- Apps/VisionOS/VisionOS/APIViews/IdentifyView.swift
- Apps/VisionOS/VisionOS/APIViews/ProfileAttributesView.swift
- Apps/VisionOS/VisionOS/APIViews/TrackEventsView.swift
- Apps/VisionOS/VisionOS/CommonViews/MainLayoutView.swift
- Apps/VisionOS/VisionOS/MainScreen.swift
- Apps/VisionOS/VisionOS/Storage/UserDefaultsCodable.swift
- Few UI changes
- Ensuring event properties are dictionary not array to be compatible with Journeys
> docs: Minor tweaks to the VisionOS Sample app

- Apps/VisionOS/README.md
Readme file for the VisionOS sample app
> docs: VisionOS Sample App Readme

- CustomerIODataPipelines.podspec
- Package.swift
- Tests/DataPipeline/DataPipelineCompatibilityTests.swift
closes: https://linear.app/customerio/issue/MBL-223/update-segment-fork
The latest fork contains the Apple privacy changes along with other improvements added that can be found here
https://github.com/customerio/cdp-analytics-swift/compare/1.5.5-cio.1...1.5.9+cio.1
> chore: update to latest analytics fork

- Apps/VisionOS/VisionOS/AppDelegate.swift
> chore: main lint fix

- Apps/VisionOS/README.md
- Apps/VisionOS/VisionOS/APIViews/IdentifyView.swift
- Apps/VisionOS/VisionOS/APIViews/ProfileAttributesView.swift
- Apps/VisionOS/VisionOS/APIViews/SDKInitializationView.swift
- Apps/VisionOS/VisionOS/APIViews/TrackEventsView.swift
- README.md
Incredibly minor updates. Ahmed's readme and application were already very easy to follow and well written!
I'll have an associated branch in the docs repo to point to the visionOS sample app and indicate that we have VisionOS support.
> docs: Vision Pro doc updates

- README.md
> docs: [docs-393] Update brand logo in readme

- Apps/CocoaPods-FCM/src/View/CustomEventView.swift
- Apps/CocoaPods-FCM/src/View/DashboardView.swift
- Tests/MessagingInApp/Core/IntegrationTest.swift
- Tests/MessagingInApp/Views/InAppMessageViewTest.swift
While QA testing the SwiftUI app, I noticed that some features were missing that the UIKit app have. I'll point these features out via comments in this PR. 
This PR doesn't introduce new ideas to the app but instead match the existing features in UIKit app.
> chore: improve swiftui app to test inline in-app like UIKit app

- .github/workflows/build-sample-apps.yml
- Updated CI configuration to build sample apps on feature branches, making it easier to test new functionality during development
> ci: build sample apps on feature branches

- .github/dependabot.yml
> ci: Updates dependabot.yml to send reviews to current squad

- Sources/MessagingInApp/Gist/Managers/InlineMessageManager.swift
- Sources/MessagingInApp/Gist/Managers/MessageManager.swift
- Sources/MessagingInApp/Gist/Managers/ModalMessageManager.swift
- Sources/MessagingInApp/State/InAppMessageMiddleware.swift
- Sources/MessagingInApp/State/InAppMessageState.swift
helps: https://linear.app/customerio/issue/MBL-492/add-the-new-in-line-components-and-gel-them-with-new-in-app-flow
changes:
- Refactored `MessageManager` so that now we have `Base` `Modal` and `Inline`
> chore: updated message managers

- CODEOWNERS
> chore: Adds CODEOWNERS file to define default code owners (EVOLV-4)

- Apps/CocoaPods-FCM/src/View/CustomEventView.swift
- Sources/MessagingInApp/Gist/Managers/InlineMessageManager.swift
- Sources/MessagingInApp/Gist/Managers/MessageManager.swift
- Sources/MessagingInApp/Gist/Managers/ModalMessageManager.swift
- Sources/MessagingInApp/Gist/Managers/Models/Message.swift
- Sources/MessagingInApp/State/InAppMessageAction.swift
- Sources/MessagingInApp/State/InAppMessageMiddleware.swift
- Sources/MessagingInApp/State/InAppMessageReducer.swift
- Sources/MessagingInApp/State/InAppMessageState.swift
- Sources/MessagingInApp/Views/GistInlineInAppMessageView.swift
- Tests/MessagingInApp/State/InAppMessageStateTests.swift
closes: https://linear.app/customerio/issue/MBL-864/support-of-multiple-in-line-messages-in-a-screen
add support to handle multiple in-line messages on a single page
> chore: support to handle multiple in-line messages

- Sources/MessagingInApp/Gist/Gist.swift
- Sources/MessagingInApp/Gist/Managers/InlineMessageManager.swift
- Sources/MessagingInApp/Gist/Managers/ModalMessageManager.swift
- Sources/MessagingInApp/State/InAppMessageMiddleware.swift
- Sources/MessagingInApp/State/InAppMessageReducer.swift
- Sources/MessagingInApp/State/InAppMessageState.swift
- Sources/MessagingInApp/Views/GistInlineInAppMessageView.swift
- Sources/MessagingInApp/Views/SwiftUIInline.swift
- Tests/MessagingInApp/Extensions/GistExtensions.swift
- Tests/MessagingInApp/State/InAppMessageStateTests.swift
changes:
- added test for inline messages use-cases 
- refactor
> chore: added tests and refactor

- .github/actions/build-sample-app/action.yml
- .github/actions/generate-sdk-size-report/action.yml
- .github/actions/setup-ios/action.yml
- .github/workflows/build-sample-apps.yml
- .github/workflows/deploy-sdk.yml
- .github/workflows/pr-helper.yml
- .github/workflows/test.yml
REF: [DX-516](https://linear.app/customerio/issue/DX-516/update-all-github-action-libraries-to-use-sha-instead-of-version) Pins GitHub Actions as part of DX-516.
> DX-516: Pin actions to SHA

- Sources/MessagingPush/RichPush/RichPushHttpClient.swift
The RichPushHttpClient instance doesn't live long enough to process the response of its requests. Which means if anything is wrong with the request, we will see no logs to understand what's going on.
This change allows us to process the response as expected without depending on the life of the RichPushHttpClient instance.
> fix: premature deallocation of the rich push http client

- scripts/check-api-changes.rb
This PR makes sure that the recommendation to update baseline API has same results locally and on CI
> chore: Fix API change detection script to match local runs with CI
